# ======================================== CHUR ZNR ========================================
# Port
server.port=8081

# ========================================
# DATASOURCE GBC 
# Base : BDSQL02
# ========================================
datasource.gbc.jdbc-url=jdbc:sqlserver://192.168.1.102:1433;instanceName=SQLEXPRESS;databaseName=BDSQL02;encrypt=true;trustServerCertificate=true
datasource.gbc.username=sa
datasource.gbc.password=CHRZ_SIGEPWEB_2024\u00E9\u00E0&&

# ========================================
# DATASOURCE GRH 
# Base : BDSQLGRH
# ========================================
datasource.grh.jdbc-url=jdbc:sqlserver://SERV-BUD-CHRZ:1433;instanceName=SQLEXPRESS;databaseName=BDSQLGRH;encrypt=true;trustServerCertificate=true
datasource.grh.username=sa
datasource.grh.password=CHRZ_SIGEPWEB_2024\u00E9\u00E0&&

# ========================================
# DATASOURCE GIM
# Base : BDSQLGIM
# ========================================
datasource.gim.jdbc-url=jdbc:sqlserver://SERV-BUD-CHRZ:1433;instanceName=SQLEXPRESS;databaseName=BDSQLGIM;encrypt=true;trustServerCertificate=true
datasource.gim.username=sa
datasource.gim.password=CHRZ_SIGEPWEB_2024\u00E9\u00E0&&

# ========================================
# DATASOURCE HistoGBK
# Base : HistoGBK
# ========================================
datasource.histo-gbk.jdbc-url=jdbc:sqlserver://SERV-BUD-CHRZ:1433;instanceName=SQLEXPRESS;databaseName=HistoGBK;encrypt=true;trustServerCertificate=true
datasource.histo-gbk.username=sa
datasource.histo-gbk.password=CHRZ_SIGEPWEB_2024\u00E9\u00E0&&


