# Port
server.port=8080

# ========================================
# DATASOURCE GBC 
# Base : BDSQL02
# ========================================
datasource.gbc.jdbc-url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=BDSQL02;encrypt=true;trustServerCertificate=true
datasource.gbc.username=sa
datasource.gbc.password=Aristide@226

# ========================================
# DATASOURCE GRH 
# Base : BDSQLGRH
# ========================================
datasource.grh.jdbc-url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=BDSQLGRH;encrypt=true;trustServerCertificate=true
datasource.grh.username=sa
datasource.grh.password=Aristide@226

# ========================================
# DATASOURCE GIM
# Base : BDSQLGIM
# ========================================
datasource.gim.jdbc-url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=BDSQLGIM;encrypt=true;trustServerCertificate=true
datasource.gim.username=sa
datasource.gim.password=Aristide@226

# ========================================
# DATASOURCE HistoGBK
# Base : HistoGBK
# ========================================
datasource.histo-gbk.jdbc-url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=HistoGBK;encrypt=true;trustServerCertificate=true
datasource.histo-gbk.username=sa
datasource.histo-gbk.password=Aristide@226
