spring.application.name=sigep
spring.profiles.active=dev

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

# Hibernate ddl auto (create, create-drop, validate, update)
# spring.datasoure.hikari.datasource-properties.includeSynonyms=true
spring.jpa.hibernate.ddl-auto=update

# Speed
spring.main.lazy-initialization=true

#################################### Gestion des logs
# Nom du fichier log
logging.file.name=logs/application.log
# Niveau de log
logging.level.root=INFO
#Rotation des logs
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=14
logging.logback.rollingpolicy.total-size-cap=200MB
# Nom des fichiers archives
logging.logback.rollingpolicy.file-name-pattern=logs/application-%d{yyyy-MM-dd}.%i.log
# Eiviter que spring et hiberneate remplissent ton log inutilement
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
#################################### Gestion des logs

