package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AffectationPatrimoine generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "AffectationPatrimoine")
public class AffectationPatrimoine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idFiche", column = @Column(name = "IdFiche", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "mle", column = @Column(name = "Mle", nullable = false, length = 50)) })
	private AffectationPatrimoineId id;

	@Column(name = "IdMagasin")
	private Integer idMagasin;

	@Column(name = "CodDirect")
	private Integer codDirect;

	@Column(name = "CodeDir", length = 6)
	private String codeDir;

	@Column(name = "CodService")
	private Integer codService;

	@Column(name = "CodeSite")
	private Integer codeSite;

	@Column(name = "CodReg")
	private Integer codReg;

	@Column(name = "CodProv")
	private Integer codProv;

	@Column(name = "QuantAffect", nullable = false)
	private int quantAffect;

	@Column(name = "NumAffecte", length = 50)
	private String numAffecte;

	@Column(name = "ValeurAffectation", nullable = false, precision = 18, scale = 0)
	private long valeurAffectation;

	@Column(name = "StatPatri", length = 2)
	private String statPatri;

	@Column(name = "Observ")
	private String observ;

	@Column(name = "StatPatriH", length = 2)
	private String statPatriH;

	@Column(name = "IdMagasinH")
	private Integer idMagasinH;

	@Column(name = "IdFicheH", precision = 18, scale = 0)
	private Long idFicheH;

	@Column(name = "MleAffectH", length = 50)
	private String mleAffectH;

	@Column(name = "CodDirectH")
	private Integer codDirectH;

	@Column(name = "CodeDirH", length = 6)
	private String codeDirH;

	@Column(name = "CodServiceH")
	private Integer codServiceH;

	@Column(name = "CodeSiteH")
	private Integer codeSiteH;

	@Column(name = "CodRegH")
	private Integer codRegH;

	@Column(name = "CodProvH")
	private Integer codProvH;

	@Column(name = "EtatActuelH", length = 50)
	private String etatActuelH;

	@Column(name = "IdInventH", precision = 18, scale = 0)
	private Long idInventH;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EtatB", nullable = false)
	private EtatBien etatBien;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFiche", nullable = false, insertable = false, updatable = false)
	private Fiches fiches;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mle", nullable = false, insertable = false, updatable = false)
	private Patrimoine patrimoine;

}