package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Agents generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Agents")
public class Agents implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "MleAgent", unique = true, nullable = false, length = 50)
	private String mleAgent;
	
	@Column(name = "Nom", nullable = false, length = 50)
	private String nom;
	
	@Column(name = "Prenom", nullable = false, length = 50)
	private String prenom;
	
	@Column(name = "Sexe", nullable = false, length = 1)
	private String sexe;
	
	@Column(name = "FonctActuelle", length = 250)
	private String fonctActuelle;
	
	@Column(name = "TitreHono", length = 150)
	private String titreHono;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdServ", nullable = false)
	private Directions directions;
	
}
