package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AmorCoefficients generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "AmorCoefficients")
public class AmorCoefficients implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "amorType", column = @Column(name = "AmorType", nullable = false, length = 1)),
			@AttributeOverride(name = "dureeMin", column = @Column(name = "DureeMin", nullable = false)) })
	private AmorCoefficientsId id;

	@Column(name = "DureeMax", nullable = false)
	private int dureeMax;

	@Column(name = "Coefficient", nullable = false, precision = 18)
	private BigDecimal coefficient;

}