package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AmorCoefficientsId generated by hbm2java
 */
@Embeddable
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AmorCoefficientsId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Column(name = "AmorType", nullable = false, length = 1)
	private char amorType;

	@Column(name = "DureeMin", nullable = false)
	private int dureeMin;

}