package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BatimentMateriauxConstructCaract generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BatimentMateriauxConstructCaract")
public class BatimentMateriauxConstructCaract implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CodMateriauxCaract", unique = true, nullable = false)
	private int codMateriauxCaract;

	@Column(name = "LibelleMateriauxCaract", length = 50)
	private String libelleMateriauxCaract;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodMateriaux", nullable = false)
	private BatimentMateriauxConstrut batimentMateriauxConstrut;

}