package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CategorieBien generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CategorieBien")
public class CategorieBien implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodCategorie", unique = true, nullable = false)
	private int codCategorie;

	@Column(name = "LibCategorieBien", length = 100)
	private String libCategorieBien;
	
	@OneToMany(mappedBy = "categorieBien")
	private List<CodeBudgType> codeBudgTypes;
}