package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CodeMateriel generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CodeMateriel")
public class CodeMateriel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodMat", unique = true, nullable = false, length = 10)
	private String codMat;

	@Column(name = "Num")
	private Integer num;

	@Column(name = "IntituleMateriel", nullable = false, length = 250)
	private String intituleMateriel;

	@Column(name = "DureeVieAn", nullable = false, precision = 6, scale = 0)
	private int dureeVieAn;

	@Column(name = "TauxAmortAn", precision = 6, insertable = false, updatable = false)
	private BigDecimal tauxAmortAn;

	@Column(name = "Art", length = 10)
	private String art;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false)
	private CodeBudgetaire codeBudgetaire;
}