package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CodeBudgetaire generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CodeBudgetaire")
public class CodeBudgetaire implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodBud", unique = true, nullable = false)
	private int codBud;

	@Column(name = "IntituleCodBud", nullable = false)
	private String intituleCodBud;

	@Column(name = "CodBudActif", nullable = false)
	private boolean codBudActif;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodTyp", nullable = false)
	private CodeBudgType codeBudgType;
}