package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CodeBudgType generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CodeBudgType")
public class CodeBudgType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodTyp", unique = true, nullable = false)
	private int codTyp;

	@Column(name = "IntituleTyp", nullable = false, length = 350)
	private String intituleTyp;

	@Column(name = "CodTypActif")
	private Boolean codTypActif;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodCategorie", nullable = false)
	private CategorieBien categorieBien;
}