package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CodeAcces generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CodeAcces")
public class CodeAcces implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdUser", unique = true, nullable = false)
	private int idUser;

	@Column(name = "UserName", nullable = false)
	private String userName;

	@Column(name = "PassWord", nullable = false)
	private String passWord;
	
	@Column(name = "MotDePasse", nullable = false, length = 256)
	private String motDePasse;

	@Column(name = "Etat", nullable = false)
	private boolean etat;

	@Column(name = "NbreConnect", nullable = false)
	private int nbreConnect;

	@Column(name = "NbreCpte")
	private Integer nbreCpte;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateChangement", length = 16)
	private Date dateChangement;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MleAgent", nullable = false)
	private Agents agents;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCodeAccessType", nullable = false)
	private CodeAccesType codeAccesType;

}