package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CodeAccesType generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CodeAccesType")
public class CodeAccesType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdCodeAccessType", unique = true, nullable = false, length = 1)
	private char idCodeAccessType;

	@Column(name = "LibCodeAccessType", length = 50)
	private String libCodeAccessType;

	@Column(name = "Descriptions", length = 350)
	private String descriptions;
}