package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Directions generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Directions")
public class Directions implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "directions"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CodDirect", unique = true, nullable = false)
	private int codDirect;
	
	@Column(name = "NomDirection", nullable = false)
	private String nomDirection;
	
	@Column(name = "Abrev", nullable = false, length = 10)
	private String abrev;
	
	@Column(name = "CodeDir", nullable = false, length = 6)
	private String codeDir;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Directions directions;

	public Directions(Directions directions, String nomDirection, String abrev, String codeDir) {
		super();
		this.directions = directions;
		this.nomDirection = nomDirection;
		this.abrev = abrev;
		this.codeDir = codeDir;
	}
}
