package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ElementEauCourante generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ElementEauCourante")
public class ElementEauCourante implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CodeEauCourant", unique = true, nullable = false)
	private int codeEauCourant;

	@Column(name = "Branchement", nullable = false, length = 250)
	private String branchement;

}