package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FicheSourceFinId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class FicheSourceFinId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "IdFiche", nullable = false, precision = 18, scale = 0)
	private long idFiche;
	
	@Column(name = "IdSourceFin", nullable = false, length = 4)
	private String idSourceFin;
}
