package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FicheEntreProvH generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "FicheEntre_ProvH")
public class FicheEntreProvH implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdFicheEntreProv", unique = true, nullable = false, length = 36)
	private String idFicheEntreProv;

	@Column(name = "AnneAcq", nullable = false)
	private short anneAcq;

	@Column(name = "EtatEntre", nullable = false, length = 50)
	private String etatEntre;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEntre", length = 23)
	private Date dateEntre;

	@Column(name = "Qtite", nullable = false)
	private int qtite;

	@Column(name = "ValUnit", nullable = false, precision = 18, scale = 0)
	private long valUnit;

	@Column(name = "ValTotal", nullable = false, precision = 37, scale = 0)
	private BigInteger valTotal;

	@Column(name = "Amrtisable")
	private Boolean amrtisable;

	@Column(name = "AmorType", length = 1)
	private Character amorType;

	@Column(name = "DureeVie", precision = 6, scale = 0)
	private Integer dureeVie;

	@Column(name = "Observ", length = 850)
	private String observ;

	@Column(name = "CodeSite")
	private Integer codeSite;

	@Column(name = "CodeUsage")
	private Integer codeUsage;

	@Column(name = "CodMatereiaux")
	private Integer codMatereiaux;

	@Column(name = "NbrePiece")
	private Integer nbrePiece;

	@Column(name = "Aniveau")
	private Boolean aniveau;

	@Column(name = "NbNiveau")
	private Integer nbNiveau;

	@Column(name = "Electrification")
	private Integer electrification;

	@Column(name = "EauCourante")
	private Integer eauCourante;

	@Column(name = "InstallTelephone")
	private Boolean installTelephone;

	@Column(name = "MarqRace", length = 150)
	private String marqRace;

	@Column(name = "Immatriculation", length = 50)
	private String immatriculation;

	@Column(name = "Format", length = 150)
	private String format;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodMat", nullable = false)
	private CodeMateriel codeMateriel;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFiche")
	private Fiches fiches;

}