package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FichesAutorisation generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Fiches_Autorisation")
public class FichesAutorisation implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "fiches"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdFiche", unique = true, nullable = false, precision = 18, scale = 0)
	private long idFiche;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Fiches fiches;
	
	@Column(name = "ObjetDepense", nullable = false, length = 850)
	private String objetDepense;
	
	@Column(name = "MontantHTVA", nullable = false, precision = 18, scale = 0)
	private long montantHtva;
	
	@Column(name = "AvecTVA", nullable = false)
	private boolean avecTva;
	
	@Column(name = "MontantTTC", nullable = false, precision = 18, scale = 0)
	private long montantTtc;
	
	@Column(name = "MontantAutori", insertable = false, updatable = false)
	private long montantAutori;

	public FichesAutorisation(Fiches fiches, String objetDepense, long montantHtva, boolean avecTva, long montantTtc,
			long montantAutori) {
		super();
		this.fiches = fiches;
		this.objetDepense = objetDepense;
		this.montantHtva = montantHtva;
		this.avecTva = avecTva;
		this.montantTtc = montantTtc;
		this.montantAutori = montantAutori;
	}
}
