package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Fiches generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Fiches")
public class Fiches implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdFiche", unique = true, nullable = false, precision = 18, scale = 0)
	private long idFiche;

	@Column(name = "NumFiche")
	private Integer numFiche;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSaisie", length = 23)
	private Date dateSaisie;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEtat", length = 23)
	private Date dateEtat;

	@Column(name = "MontantFiche", precision = 18, scale = 0)
	private Long montantFiche;

	@Column(name = "IdTypeAcq")
	private Integer idTypeAcq;

	@Column(name = "CodSourceFin", length = 4)
	private String codSourceFin;

	@Column(name = "Affect")
	private Boolean affect;

	@Column(name = "IdMagasin")
	private Integer idMagasin;

	@Column(name = "CodDirect")
	private Integer codDirect;

	@Column(name = "IdService")
	private Integer idService;

	@Column(name = "CodProv")
	private Integer codProv;

	@Column(name = "MleAgent", length = 50)
	private String mleAgent;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateAffect", length = 23)
	private Date dateAffect;

	@Column(name = "CodDirectOrigi")
	private Integer codDirectOrigi;

	@Column(name = "IdServiceOrigi")
	private Integer idServiceOrigi;

	@Column(name = "CodProvOrigi")
	private Integer codProvOrigi;

	@Column(name = "CodeSite")
	private Integer codeSite;

	@Column(name = "ComplementMle", insertable = false, updatable = false)
	private String complementMle;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateRetourPossible", length = 23)
	private Date dateRetourPossible;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateRetourEffective", length = 23)
	private Date dateRetourEffective;

	@Column(name = "typSortie")
	private Short typSortie;

	@Column(name = "IdFicheH", precision = 18, scale = 0)
	private Long idFicheH;

	@Column(name = "IdSourceFin")
	private Integer idSourceFin;

	@Column(name = "IdBudget", nullable = false)
	private int idBudget;

	@Column(name = "fonctSigna1", length = 150)
	private String fonctSigna1;

	@Column(name = "prenomNomSigna1", length = 100)
	private String prenomNomSigna1;

	@Column(name = "titreHonoSigna1", length = 50)
	private String titreHonoSigna1;

	@Column(name = "fonctSigna2", length = 150)
	private String fonctSigna2;

	@Column(name = "prenomNomSigna2", length = 100)
	private String prenomNomSigna2;

	@Column(name = "titreHonoSigna2", length = 50)
	private String titreHonoSigna2;

	@Column(name = "fonctSigna3", length = 150)
	private String fonctSigna3;

	@Column(name = "prenomNomSigna3", length = 100)
	private String prenomNomSigna3;

	@Column(name = "titreHonoSigna3", length = 50)
	private String titreHonoSigna3;

	@Column(name = "NumBE", precision = 18, scale = 0)
	private Long numBe;

	@Column(name = "BENum", length = 50)
	private String benum;

	@Column(name = "NbBiens", nullable = false)
	private int nbBiens;

	@Column(name = "NumeroFiche", insertable = false, updatable = false)
	private String numeroFiche;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEntreSortie", nullable = false, length = 23)
	private Date dateEntreSortie;

	@Column(name = "BienEnMagasin", nullable = false)
	private boolean bienEnMagasin;
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "fiches")
	private FichesAutorisation fichesAutorisation;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodCategorie")
	private CategorieBien categorieBien;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EtatFiche")
	private EtatFiche etatFiche;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFourn")
	private Fournisseurs fournisseurs;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdTypFiche", nullable = false)
	private TypFiche typFiche;
}