package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Fournisseurs generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Fournisseurs")
public class Fournisseurs implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdFourn", unique = true, nullable = false, precision = 18, scale = 0)
	private long idFourn;

	@Column(name = "Fournisseur", nullable = false, length = 250)
	private String fournisseur;

	@Column(name = "NumIFU", length = 50)
	private String numIfu;

	@Column(name = "TelFourn", length = 50)
	private String telFourn;

	@Column(name = "BPFourn", length = 250)
	private String bpfourn;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TypeF", nullable = false)
	private FournisseurType fournisseurType;

}