package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * HistoEtat generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "HistoEtat")
public class HistoEtat implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "etat", column = @Column(name = "Etat", nullable = false, length = 1)),
			@AttributeOverride(name = "idFiche", column = @Column(name = "IdFiche", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "dateEtat", column = @Column(name = "DateEtat", nullable = false, length = 23)) })
	private HistoEtatId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Etat", nullable = false, insertable = false, updatable = false)
	private EtatFiche etatFiche;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFiche", nullable = false, insertable = false, updatable = false)
	private Fiches fiches;

}