package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * HistoEtatId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class HistoEtatId implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "Etat", nullable = false, length = 1)
	private String etat;
	
	@Column(name = "IdFiche", nullable = false, precision = 18, scale = 0)
	private long idFiche;
	
	@Column(name = "DateEtat", nullable = false, length = 23)
	private Date dateEtat;
}
