package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * InventairePatrimoine generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "InventairePatrimoine")
public class InventairePatrimoine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idInvent", column = @Column(name = "IdInvent", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "mle", column = @Column(name = "Mle", nullable = false, length = 50)) })
	private InventairePatrimoineId id;

	@Column(name = "etatBien", length = 50)
	private String etatBien;

	@Column(name = "QtiteTheorique", nullable = false)
	private int qtiteTheorique;

	@Column(name = "QtitePhysique")
	private Integer qtitePhysique;

	@Column(name = "etatBienInvent", length = 50)
	private String etatBienInvent;

	@Column(name = "ObervationInvent")
	private String obervationInvent;

	@Column(name = "idMagasin")
	private Integer idMagasin;

	@Column(name = "codDirect")
	private Integer codDirect;

	@Column(name = "codProv")
	private Integer codProv;

	@Column(name = "codSite")
	private Integer codSite;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdInvent", nullable = false, insertable = false, updatable = false)
	private Inventaire inventaire;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mle", nullable = false, insertable = false, updatable = false)
	private Patrimoine patrimoine;

}