package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Inventaire generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Inventaire")
public class Inventaire implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdInvent", unique = true, nullable = false, precision = 18, scale = 0)
	private long idInvent;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateInvent", nullable = false, length = 23)
	private Date dateInvent;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEtat", nullable = false, length = 23)
	private Date dateEtat;

	@Column(name = "EnStock", nullable = false)
	private boolean enStock;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EtatInvent", nullable = false)
	private EtatFiche etatFiche;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdTypeInvent", nullable = false)
	private InventaireType inventaireType;
}