package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * LivreJournal generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "LivreJournal")
public class LivreJournal implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IdJournal", unique = true, nullable = false, precision = 18, scale = 0)
	private long idJournal;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateValide", nullable = false, length = 23)
	private Date dateValide;

	@Column(name = "Entree", nullable = false)
	private boolean entree;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFiche", nullable = false)
	private Fiches fiches;

}