package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * NiveauCodeBudgetaire generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "NiveauCodeBudgetaire")
public class NiveauCodeBudgetaire implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "Niveau", unique = true, nullable = false)
	private int niveau;

	@Column(name = "IntituleNiveau")
	private String intituleNiveau;

	@Column(name = "Description")
	private String description;

}