package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PatrimoineMateriels generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "PatrimoineMateriels")
public class PatrimoineMateriels implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "patrimoine"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Mle", unique = true, nullable = false, length = 50)
	private String mle;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Patrimoine patrimoine;
	
	@Column(name = "MarqRace", length = 150)
	private String marqRace;
	
	@Column(name = "Immatriculation", length = 50)
	private String immatriculation;
	
	@Column(name = "IdMagasin")
	private Integer idMagasin;
	
	@Column(name = "Format", length = 150)
	private String format;

	public PatrimoineMateriels(Patrimoine patrimoine, String marqRace, String immatriculation, Integer idMagasin,
			String format) {
		super();
		this.patrimoine = patrimoine;
		this.marqRace = marqRace;
		this.immatriculation = immatriculation;
		this.idMagasin = idMagasin;
		this.format = format;
	}
}
