package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PatrimoineStatut generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PatrimoineStatut")
public class PatrimoineStatut implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "StatPatri", unique = true, nullable = false, length = 2)
	private String statPatri;

	@Column(name = "LibelStatPatri", length = 50)
	private String libelStatPatri;
}