package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Patrimoine generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Patrimoine")
public class Patrimoine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "Mle", unique = true, nullable = false, length = 50)
	private String mle;

	@Column(name = "CodStruct", nullable = false, length = 6)
	private String codStruct;

	@Column(name = "AnneAcq", nullable = false)
	private short anneAcq;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEntre", nullable = false, length = 23)
	private Date dateEntre;

	@Column(name = "Quantieme", nullable = false)
	private int quantieme;

	@Column(name = "ValUnit", nullable = false, precision = 18, scale = 0)
	private long valUnit;

	@Column(name = "DureeVie", nullable = false, precision = 6, scale = 0)
	private int dureeVie;

	@Column(name = "Amrtisable", nullable = false)
	private boolean amrtisable;

	@Column(name = "AmorType", length = 1)
	private Character amorType;

	@Column(name = "TauxAmort", precision = 6, insertable = false, updatable = false)
	private BigDecimal tauxAmort;

	@Column(name = "Format", length = 150)
	private String format;

	@Column(name = "IdMagasin")
	private Integer idMagasin;

	@Column(name = "MleAffect", length = 50)
	private String mleAffect;

	@Column(name = "CodDirect")
	private Integer codDirect;

	@Column(name = "CodeDir", length = 6)
	private String codeDir;

	@Column(name = "CodService")
	private Integer codService;

	@Column(name = "CodReg")
	private Integer codReg;

	@Column(name = "CodProv")
	private Integer codProv;

	@Column(name = "EtatActuel", length = 50)
	private String etatActuel;

	@Column(name = "IdInvent", precision = 18, scale = 0)
	private Long idInvent;

	@Column(name = "IdFicheEntreProv", length = 36)
	private String idFicheEntreProv;

	@Column(name = "IdFicheEnCours", precision = 18, scale = 0)
	private Long idFicheEnCours;

	@Column(name = "NomAgentUtil", length = 150)
	private String nomAgentUtil;

	@Column(name = "MleAgentUtil", length = 50)
	private String mleAgentUtil;

	@Column(name = "ValActuelle", precision = 18, scale = 0, insertable = false, updatable = false)
	private Long valActuelle;

	@Column(name = "DansInventaire", nullable = false)
	private boolean dansInventaire;
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "patrimoine")
	private PatrimoineBatiments patrimoineBatiments;
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "patrimoine")
	private PatrimoineMateriels patrimoineMateriels;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodCategorie", nullable = false)
	private CategorieBien categorieBien;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodMat", nullable = false)
	private CodeMateriel codeMateriel;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EtatEntre", nullable = false)
	private EtatBien etatBien;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFicheAffec")
	private Fiches fichesByIdFicheAffec;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFiche", nullable = false)
	private Fiches fichesByIdFiche;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StatPatri")
	private PatrimoineStatut patrimoineStatut;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodeSite")
	private Sites sites;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodSourceFin", nullable = false)
	private SourceFinancement sourceFinancement;
}