package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PatrimoineBatiments generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "PatrimoineBatiments")
public class PatrimoineBatiments implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "patrimoine"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Mle", unique = true, nullable = false, length = 50)
	private String mle;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Patrimoine patrimoine;

	@Column(name = "NbrePiece")
	private Integer nbrePiece;

	@Column(name = "InstallTelephone")
	private Boolean installTelephone;

	@Column(name = "Aniveau")
	private Boolean aniveau;

	@Column(name = "NbNiveau")
	private Integer nbNiveau;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodMatereiaux", nullable = false)
	private BatimentMateriauxConstrut batimentMateriauxConstrut;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodeUsage", nullable = false)
	private BatimentUsages batimentUsages;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EauCourante")
	private ElementEauCourante elementEauCourante;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Electrification")
	private ElementElectricite elementElectricite;

}