package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PatrimoineSortie generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PatrimoineSortie")
public class PatrimoineSortie implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idFiche", column = @Column(name = "IdFiche", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "mle", column = @Column(name = "Mle", nullable = false, length = 50)) })
	private PatrimoineSortieId id;

	@Column(name = "ValeurAffectation", precision = 18, scale = 0)
	private Long valeurAffectation;

	@Column(name = "Observ", length = 850)
	private String observ;

	@Column(name = "Temporaire")
	private Boolean temporaire;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateRetourPossible", length = 23)
	private Date dateRetourPossible;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateRetourEffective", length = 23)
	private Date dateRetourEffective;

	@Column(name = "EtatRetour", length = 50)
	private String etatRetour;

	@Column(name = "ObservRetour", length = 850)
	private String observRetour;

	@Column(name = "IdFicheH", precision = 18, scale = 0)
	private Long idFicheH;

	@Column(name = "StatPatriH", length = 2)
	private String statPatriH;

	@Column(name = "MleAffectH", length = 50)
	private String mleAffectH;

	@Column(name = "IdMagasinH")
	private Integer idMagasinH;

	@Column(name = "CodeSite")
	private Integer codeSite;

	@Column(name = "CodDirectH")
	private Integer codDirectH;

	@Column(name = "CodServiceH")
	private Integer codServiceH;

	@Column(name = "CodProvH")
	private Integer codProvH;

	@Column(name = "etatActuelH", length = 50)
	private String etatActuelH;

	@Column(name = "IdInventH", precision = 18, scale = 0)
	private Long idInventH;

	@Column(name = "IdFicheRetour", precision = 18, scale = 0)
	private Long idFicheRetour;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EtatB", nullable = false)
	private EtatBien etatBien;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFiche", nullable = false, insertable = false, updatable = false)
	private Fiches fiches;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mle", nullable = false, insertable = false, updatable = false)
	private Patrimoine patrimoine;

}