package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Pieces generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Pieces")
public class Pieces implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idPieces", unique = true, nullable = false, precision = 18, scale = 0)
	private long idPieces;

	@Column(name = "NaturePiece", length = 50)
	private String naturePiece;
}