package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PiecesFiche generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PiecesFiche")
public class PiecesFiche implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idPieceFiche", unique = true, nullable = false, precision = 18, scale = 0)
	private long idPieceFiche;

	@Column(name = "RefPiece", length = 50)
	private String refPiece;

	@Temporal(TemporalType.DATE)
	@Column(name = "DatePiece", length = 10)
	private Date datePiece;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPieces", nullable = false)
	private Pieces pieces;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFiche")
	private Fiches fiches;

}