package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Province generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Province")
public class Province implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CodProv", unique = true, nullable = false)
	private int codProv;

	@Column(name = "Provinc", nullable = false)
	private String provinc;

	@Column(name = "ChefLieu", nullable = false)
	private String chefLieu;

	@Column(name = "articleProv", nullable = false, length = 6)
	private String articleProv;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodReg", nullable = false)
	private Region region;
}