package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Region generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Region")
public class Region implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodReg", unique = true, nullable = false)
	private int codReg;

	@Column(name = "Rgion")
	private String rgion;

	@Column(name = "ChefLieu")
	private String chefLieu;

	@Column(name = "articleRegion", nullable = false, length = 6)
	private String articleRegion;

}