package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Service generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Service", uniqueConstraints = @UniqueConstraint(columnNames = { "CodDirect", "CodServ" }))
public class Service implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdService", unique = true, nullable = false)
	private int idService;

	@Column(name = "CodServ", nullable = false)
	private int codServ;

	@Column(name = "NomService", nullable = false)
	private String nomService;

	@Column(name = "AbrevService", nullable = false, length = 20)
	private String abrevService;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodDirect", nullable = false)
	private Directions directions;

}