package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * SignataireParDefaut generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "SignataireParDefaut")
public class SignataireParDefaut implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodSignataire", unique = true, nullable = false, length = 1)
	private String codSignataire;

	@Column(name = "fonctSigna1", length = 150)
	private String fonctSigna1;

	@Column(name = "prenomNomSigna1", length = 100)
	private String prenomNomSigna1;

	@Column(name = "titreHonoSigna1", length = 50)
	private String titreHonoSigna1;

	@Column(name = "fonctSigna2", length = 150)
	private String fonctSigna2;

	@Column(name = "prenomNomSigna2", length = 100)
	private String prenomNomSigna2;

	@Column(name = "titreHonoSigna2", length = 50)
	private String titreHonoSigna2;

	@Column(name = "fonctSigna3", length = 150)
	private String fonctSigna3;

	@Column(name = "prenomNomSigna3", length = 100)
	private String prenomNomSigna3;

	@Column(name = "titreHonoSigna3", length = 50)
	private String titreHonoSigna3;

}