package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Sites generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Sites")
public class Sites implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CodeSite", unique = true, nullable = false)
	private int codeSite;

	@Column(name = "NomSite", length = 50)
	private String nomSite;

	@Column(name = "Secteur_Cadastre", length = 50)
	private String secteurCadastre;

	@Column(name = "Section_Cadastre", length = 50)
	private String sectionCadastre;

	@Column(name = "Lot_Cadastre", length = 50)
	private String lotCadastre;

	@Column(name = "Parcelle_Cadastre", length = 50)
	private String parcelleCadastre;

	@Column(name = "AutresPrecision", length = 150)
	private String autresPrecision;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", length = 23)
	private Date dateCreation;

	@Column(name = "Superficie", precision = 18)
	private BigDecimal superficie;

	@Column(name = "CoutTerrain", precision = 18, scale = 0)
	private Long coutTerrain;

	@Column(name = "IdTypeAcq")
	private Integer idTypeAcq;

	@Column(name = "NombreMaterielH")
	private Integer nombreMaterielH;

	@Column(name = "NbreBatimentH")
	private Integer nbreBatimentH;

	@Column(name = "NbreUE")
	private Integer nbreUe;

	@Column(name = "NbreAutreInfras")
	private Integer nbreAutreInfras;

	@Column(name = "articleSite", nullable = false, length = 6)
	private String articleSite;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDepart", nullable = false)
	private Departement departement;
	
	@OneToMany(mappedBy = "sites")
	private List<Patrimoine> patrimoines;
}