package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * SourceFinancement generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "SourceFinancement")
public class SourceFinancement implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodSourceFin", unique = true, nullable = false, length = 4)
	private String codSourceFin;

	@Column(name = "LibSourceFin", nullable = false, length = 150)
	private String libSourceFin;

	@Column(name = "AbrevSourceFin", length = 10)
	private String abrevSourceFin;
	
	@OneToMany(mappedBy = "sourceFinancement")
	List<Patrimoine> patrimoines;
}