package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * T13 generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "T13")
public class T13 implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodeMat", unique = true, nullable = false, length = 9)
	private String codeMat;

	@Column(name = "ANNEACQ", precision = 18, scale = 0)
	private Long anneacq;

}