package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TableE generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "TableE")
public class TableE implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idInvent", column = @Column(name = "IdInvent", precision = 18, scale = 0)),
			@AttributeOverride(name = "mle", column = @Column(name = "Mle", length = 50)),
			@AttributeOverride(name = "etatBien", column = @Column(name = "etatBien", length = 50)),
			@AttributeOverride(name = "qtitePhysique", column = @Column(name = "QtitePhysique")),
			@AttributeOverride(name = "etatBienInvent", column = @Column(name = "etatBienInvent", length = 50)),
			@AttributeOverride(name = "qtiteTheorique", column = @Column(name = "QtiteTheorique")),
			@AttributeOverride(name = "obervationInvent", column = @Column(name = "ObervationInvent")),
			@AttributeOverride(name = "idMagasin", column = @Column(name = "idMagasin")),
			@AttributeOverride(name = "codDirect", column = @Column(name = "codDirect")),
			@AttributeOverride(name = "codProv", column = @Column(name = "codProv")),
			@AttributeOverride(name = "codSite", column = @Column(name = "codSite")) })
	private TableEId id;
}
