package com.sigep.gim.entity;
// Generated 5 fvr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TableRapport generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Table_Rapport")
public class TableRapport implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "Mle", unique = true, nullable = false, length = 50)
	private String mle;

	@Column(name = "ID", nullable = false, length = 36)
	private String id;

	@Column(name = "IdFiche", precision = 18, scale = 0)
	private Long idFiche;

	@Column(name = "CodCategorie")
	private Integer codCategorie;

	@Column(name = "CodStruct", length = 6)
	private String codStruct;

	@Column(name = "CodSourceFin", length = 4)
	private String codSourceFin;

	@Column(name = "CodMat", length = 10)
	private String codMat;

	@Column(name = "AnneAcq")
	private Short anneAcq;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEntre", length = 23)
	private Date dateEntre;

	@Column(name = "Quantieme")
	private Integer quantième;

	@Column(name = "EtatEntre", length = 50)
	private String etatEntre;

	@Column(name = "ValUnit", precision = 18, scale = 0)
	private Long valUnit;

	@Column(name = "DureeVie", precision = 6, scale = 0)
	private Integer dureeVie;

	@Column(name = "Amrtisable")
	private Boolean amrtisable;

	@Column(name = "AmorType", length = 1)
	private Character amorType;

	@Column(name = "Format", length = 150)
	private String format;

	@Column(name = "StatPatri", length = 2)
	private String statPatri;

	@Column(name = "IdMagasin")
	private Integer idMagasin;

	@Column(name = "IdFicheAffec", precision = 18, scale = 0)
	private Long idFicheAffec;

	@Column(name = "MleAffect", length = 50)
	private String mleAffect;

	@Column(name = "CodDirect")
	private Integer codDirect;

	@Column(name = "CodeDir", length = 6)
	private String codeDir;

	@Column(name = "CodService")
	private Integer codService;

	@Column(name = "CodeSite")
	private Integer codeSite;

	@Column(name = "CodReg")
	private Integer codReg;

	@Column(name = "CodProv")
	private Integer codProv;

	@Column(name = "EtatActuel", length = 50)
	private String etatActuel;

	@Column(name = "IdInvent", precision = 18, scale = 0)
	private Long idInvent;

	@Column(name = "IdFicheEntreProv", nullable = false, length = 36)
	private String idFicheEntreProv;

	@Column(name = "IdFicheEnCours", precision = 18, scale = 0)
	private Long idFicheEnCours;

	@Column(name = "NomAgentUtil", length = 150)
	private String nomAgentUtil;

	@Column(name = "MleAgentUtil", length = 50)
	private String mleAgentUtil;

	@Column(name = "MarqueType", length = 150)
	private String marqueType;

}