package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TableEId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class TableEId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "IdInvent", precision = 18, scale = 0)
	private Long idInvent;
	
	@Column(name = "Mle", length = 50)
	private String mle;
	
	@Column(name = "etatBien", length = 50)
	private String etatBien;
	
	@Column(name = "QtitePhysique")
	private Integer qtitePhysique;
	
	@Column(name = "etatBienInvent", length = 50)
	private String etatBienInvent;
	
	@Column(name = "QtiteTheorique")
	private Integer qtiteTheorique;
	
	@Column(name = "ObervationInvent")
	private String obervationInvent;
	
	@Column(name = "idMagasin")
	private Integer idMagasin;
	
	@Column(name = "codDirect")
	private Integer codDirect;
	
	@Column(name = "codProv")
	private Integer codProv;
	
	@Column(name = "codSite")
	private Integer codSite;
}
