package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Temtable generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "TEMTABLE")
public class Temtable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "Mle", unique = true, nullable = false, length = 50)
	private String mle;
	
	@Column(name = "NumAffect", length = 50)
	private String numAffect;
	
	@Column(name = "Designation", length = 50)
	private String designation;
	
	@Column(name = "Type", length = 50)
	private String type;
	
	@Column(name = "Etat", length = 50)
	private String etat;
	
	@Column(name = "Format", length = 50)
	private String format;
	
	@Column(name = "DateAcq", length = 50)
	private String dateAcq;
	
	@Column(name = "Service", length = 50)
	private String service;
	
	@Column(name = "NomUtil", length = 50)
	private String nomUtil;
}
