package com.sigep.gim.entity;
// Generated 5 f�vr. 2026, 12:50:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TypeSortie generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "TypeSortie")
public class TypeSortie implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "typSortie", unique = true, nullable = false)
	private short typSortie;
	
	@Column(name = "LibSortie", nullable = false, length = 60)
	private String libSortie;
	
	@Column(name = "Sorti", nullable = false, length = 4)
	private String sorti;
}
