package com.sigep.grh.entity;
// Generated 5 f�vr. 2026, 12:33:39 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AccesCode generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "AccesCode")
public class AccesCode implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "UserName", unique = true, nullable = false, length = 5)
	private String userName;
	
	@Column(name = "MotPasse", nullable = false, length = 256)
	private String motPasse = "l5ZGW6tjHePE+jeHtULffA==";
	
	@Column(name = "MotDePasse", nullable = false, length = 256)
	private String motDePasse;
	
	@Column(name = "Statu")
	private String statu;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateChangement", length = 16)
	private Date dateChangement;
	
	@Column(name = "NbreDeFois")
	private Short nbreDeFois;
	
	@Column(name = "rangCod")
	private Integer rangCod;
	
	@Column(name = "ID")
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Code")
	private AccesCodeNiveau accesCodeNiveau;
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "Mle")
	//private Agents agents;
	@Column(name = "Mle")
	private Integer mle; // RELATION A REFAIRE SI AGENT OK
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Grpe")
	private GrpeCode grpeCode;
}
