package com.sigep.grh.entity;
// Generated 5 f�vr. 2026, 12:33:39 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * GrpeCode generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "GrpeCode")
public class GrpeCode implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "grpe", unique = true, nullable = false)
	private String grpe;
	
	@Column(name = "LibelleGrpe")
	private String libelleGrpe;
}
