package com.sigep.gbc.entity;
// Generated 16 ao�t 2022, 19:00:48 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AccesLigneBudgetaire generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "AccesLigneBudgetaire")
public class AccesLigneBudgetaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userName", column = @Column(name = "UserName", nullable = false, length = 5)),
			@AttributeOverride(name = "numNo", column = @Column(name = "NumNo", nullable = false)),
			@AttributeOverride(name = "gestion", column = @Column(name = "Gestion", nullable = false)) })
	private AccesLigneBudgetaireId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false, insertable = false, updatable = false)
	private Gestion gestion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumNo", nullable = false, insertable = false, updatable = false)
	private NomenclatureD nomenclatureD;
	
	@Column(name="IdBudgett")
	private int idBudgett;
}
