package com.sigep.gbc.entity;
// Generated 16 ao�t 2022, 19:00:48 by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AccesLigneBudgetaireId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class AccesLigneBudgetaireId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "UserName", nullable = false, length = 5)
	private String userName;
	
	@Column(name = "NumNo", nullable = false)
	private String numNo;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;
}
