package com.sigep.gbc.entity;
// Generated 28 juin 2022, 18:45:14 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AccesCode generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "AccesCode")
public class AccesCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "UserName", unique = true, nullable = false, length = 5)
	private String userName;
	
	@Column(name = "MotPasse", nullable = false, length = 256)
	private String motPasse = "l5ZGW6tjHePE+jeHtULffA==";
	
	@Column(name = "MotDePasse", nullable = true, length = 256)
	private String motDePasse;
	
	@Column(name = "Statu")
	private String statu;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateChangement", length = 16)
	private Date dateChangement;
	
	@Column(name = "NbreDeFois")
	private Short nbreDeFois;
	
	@Column(name = "rangCod")
	private Integer rangCod;
	
	@Column(name = "ID")
	private Integer id;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreat", nullable = false, length = 23)
	private Date dateCreat;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Code")
	private AccesCodeNiveau accesCodeNiveau;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mle")
	private Agents agents;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Grpe")
	private GrpeCode grpeCode;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accesCode")
	private List<MandatLettrages> mandatLettrages = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accesCode")
	private List<CaisseSession> caisseSessions = new ArrayList<>();
}
