package com.sigep.gbc.entity;
// Generated 28 juin 2022, 18:45:14 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AccesCodeNiveau generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "AccesCodeNiveau")
public class AccesCodeNiveau implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "Code", unique = true, nullable = false)
	private String code;
	
	@Column(name = "IntituleCode")
	private String intituleCode;
	
	@Column(name = "NomStruct")
	private String nomStruct;
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accesCodeNiveau")
	private List<AccesCode> accesCodes = new ArrayList<>();
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "GrpeCodeAccesNiveau", 
			joinColumns = {@JoinColumn(name = "Code", nullable = false, updatable = false) },
			inverseJoinColumns = {@JoinColumn(name = "grpe", nullable = false, updatable = false) }
	)
	private List<GrpeCode> grpeCodes = new ArrayList<>();
	
	public void addAcccesCode(AccesCode accesCode) {
		accesCodes.add(accesCode);
	}
	
	public void removeAccesCode(AccesCode accesCode) {
		accesCodes.remove(accesCode);
	}
	
	public void addGrpeCode(GrpeCode grpeCode) {
		grpeCodes.add(grpeCode);
	}
	
	public void removeGrpeCode(GrpeCode grpeCode) {
		grpeCodes.remove(grpeCode);
	}

}
