package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AcompteFrais generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "AcompteFrais", schema = "Elev")
public class AcompteFrais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdAcompte", unique = true, nullable = false, precision = 18, scale = 0)
	private long idAcompte;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Dateversement", nullable = false, length = 23)
	private Date dateversement;

	@Column(name = "Acompte", nullable = false, precision = 18, scale = 0)
	private long acompte;

	@Column(name = "NumAcpte", nullable = false)
	private int numAcpte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodRecouv", nullable = false)
	private Recouvrements recouvrements;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdTitre")
	private TitreDetail titreDetail;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodTitr")
	private TitreEmis titreEmis;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idInscritPour", nullable = false)
	private InscritPour inscritPour;
}
