package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ActeNature generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "ActeNature", schema = "dbo")
public class ActeNature implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdActe", unique = true, nullable = false)
	private Integer idActe;
	
	@Column(name = "Acte", nullable = false, length = 150)
	private String acte;
	
	@Column(name = "ActeTitre", nullable = false, length = 50)
	private String acteTitre;
	
	@Column(name = "ActeNumComplema", length = 50)
	private String acteNumComplema;
	
	@Column(name = "dernierArticleDebloc", length = 250)
	private String dernierArticleDebloc;

	@Column(name = "dernierArticleReam", length = 250)
	private String dernierArticleReam;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acteNature")
	private List<ReamgmtActe> reamgmtActes = new ArrayList<>();

	public ActeNature(String acte, String acteTitre, String acteNumComplema, String dernierArticleDebloc,
			String dernierArticleReam, List<ReamgmtActe> reamgmtActes) {
		super();
		this.acte = acte;
		this.acteTitre = acteTitre;
		this.acteNumComplema = acteNumComplema;
		this.dernierArticleDebloc = dernierArticleDebloc;
		this.dernierArticleReam = dernierArticleReam;
		this.reamgmtActes = reamgmtActes;
	}
}
