package com.sigep.gbc.entity;
// Generated 28 juin 2022, 18:45:14 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Agents generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Agents")
public class Agents implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "destinataires"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Mle", unique = true, nullable = false, precision = 18, scale = 0)
	private long mle;
	
	@Column(name = "Nom")
	private String nom;
	
	@Column(name = "Prenom")
	private String prenom;
	
	@Column(name = "Sexe", nullable = false, length = 1)
	private char sexe;
	
	@Column(name = "Signataire")
	private String signataire;
	
	@Column(name = "TitreHonoSign")
	private String titreHonoSign;
	
	@Column(name = "Actif", nullable = false)
	private boolean actif;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdService")
	private DirectionService directionService;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agents")
	private List<AccesCode> accesCodes = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agents")
	private List<TitreDetail> titreDetails = new ArrayList<>();
	
	
	public void addAcccesCode(AccesCode accesCode) {
		accesCodes.add(accesCode);
	}
	
	public void removeAccesCode(AccesCode accesCode) {
		accesCodes.remove(accesCode);
	}
}
