package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Ampliataires generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Ampliataires", schema = "dbo")
public class Ampliataires implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "Amp", unique = true, nullable = false)
	private String amp;
	
	@Column(name = "AmpLibe")
	private String ampLibe;

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "ampliataires")
	private List<Penalite> penalites = new ArrayList<>();
}
