package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AnneeScolaire generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "AnneeScolaire", schema = "Elev")
public class AnneeScolaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "AnneD", unique = true, nullable = false)
	private int anneD;
	
	@Column(name = "AnneF", nullable = false)
	private int anneF;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaire")
	private List<InfoInscriptionEleve> infoInscriptionEleves = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaire")
	private List<InscritPour> inscritPours = new ArrayList<>();
}
