package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Avenant generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Avenant", schema = "dbo")
public class Avenant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdAvenant", unique = true, nullable = false)
	private Integer idAvenant;
	
	@Column(name = "Num")
	private Integer num;

	@Column(name = "Montant", precision = 18, scale = 0)
	private Long montant;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateApprob", length = 16)
	private Date dateApprob;

	@Column(name = "DelaiNbre", precision = 18, scale = 0)
	private Long delaiNbre;

	@Column(name = "DelaiText")
	private String delaiText;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSaisie", length = 16)
	private Date dateSaisie;

	@Column(name = "Objet")
	private String objet;

	@Column(name = "Avenant")
	private Boolean avenant;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdContrat")
	private Contrats contrats;

	public Avenant(Integer num, Long montant, Date dateApprob, Long delaiNbre, String delaiText, Date dateSaisie,
			String objet, Boolean avenant, Contrats contrats) {
		super();
		this.num = num;
		this.montant = montant;
		this.dateApprob = dateApprob;
		this.delaiNbre = delaiNbre;
		this.delaiText = delaiText;
		this.dateSaisie = dateSaisie;
		this.objet = objet;
		this.avenant = avenant;
		this.contrats = contrats;
	}
}
