package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.annotation.ReadOnlyProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BordTransmis generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BordTransmis", schema = "dbo")
public class BordTransmis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodBord", unique = true, nullable = false, precision = 18, scale = 0)
	private long codBord;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;
	
	@Column(name = "Dossier")
	private String dossier;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", length = 23)
	private Date dateCreation;
	
	@Column(name = "Expeditaire")
	private String expeditaire;
	
	@Column(name = "Destinataire")
	private String destinataire;
	
	@Column(name = "IdLogin", nullable = false, length = 5)
	private String idLogin;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateReception", length = 23)
	private Date dateReception;
	
	@Column(name = "IdLoginRecep", length = 5)
	private String idLoginRecep;
	
	@Column(name = "Numero")
	private Integer numero;
	
	@ReadOnlyProperty
	@Column(name = "BordNumero", length = 250, insertable = false, updatable = false)
	private String bordNumero;
	
	@Column(name = "IdentiteRecept", length = 150)
	private String identiteRecept;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "BordTransEng", schema = "dbo", 
			joinColumns = {@JoinColumn(name = "CodBord", nullable = false, updatable = false) }, 
			inverseJoinColumns = {@JoinColumn(name = "NumBE", nullable = false, updatable = false) })
	private List<Engagements> engagementsBordTransEng = new ArrayList<>();
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "BordTransMand", schema = "dbo", 
			joinColumns = {@JoinColumn(name = "CodBord") }, 
			inverseJoinColumns = {@JoinColumn(name = "NumMand") })
	private List<Mandats> mandatsBordTransMand = new ArrayList<>();
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "BordTransLiq", schema = "dbo", 
			joinColumns = {@JoinColumn(name = "CodBord") }, 
			inverseJoinColumns = {@JoinColumn(name = "CodLiq") })
	private List<Mandats> mandatsBordTransLiq = new ArrayList<>();
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "BordTrans_MotifRejet", schema = "dbo", 
			joinColumns = {@JoinColumn(name = "CodBord") }, 
			inverseJoinColumns = {@JoinColumn(name = "Id_motif") })
	private List<MotifsRejetDossier> motifsRejetDossiers = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bordTransmis")
	private List<TitreDetail> titreDetails = new ArrayList<>();
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "bordTransmis")
	//private List<Engagements> engagements = new ArrayList<>();
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "bordTransmis")
	//private List<Mandats> mandats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bordTransmis")
	private List<BordTransRecouv> bordTransRecouvs = new ArrayList<>();
}
