package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BordTitre generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BordTitre", schema = "dbo")
public class BordTitre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idbord", column = @Column(name = "IDbord", nullable = false, length = 36)),
			@AttributeOverride(name = "idDetailTitre", column = @Column(name = "IdDetailTitre", nullable = false, precision = 18, scale = 0)) })
	private BordTitreId id;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePaieRecouv", length = 23)
	private Date datePaieRecouv;
	
	@Column(name = "Observation", length = 550)
	private String observation;
	
	@Column(name = "ActifSurBord", nullable = false)
	private boolean actifSurBord;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDbord", nullable = false, insertable = false, updatable = false)
	private BordereauEmismandats bordereauEmismandats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDetailTitre", nullable = false, insertable = false, updatable = false)
	private TitreDetail titreDetail;
}
