package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BordTransRecouv generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BordTransRecouv", schema = "dbo")
public class BordTransRecouv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codBord", column = @Column(name = "CodBord", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "codRecouv", column = @Column(name = "CodRecouv", nullable = false, length = 36)) })
	private BordTransRecouvId id;
	
	@Column(name = "EstActif", nullable = false)
	private boolean estActif;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBord", nullable = false, insertable = false, updatable = false)
	private BordTransmis bordTransmis;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodRecouv", nullable = false, insertable = false, updatable = false)
	private Recouvrements recouvrements;
}
