package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BordereauEmismandats generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "BordereauEmismandats", schema = "dbo")
public class BordereauEmismandats implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	private String id;
	
	@Column(name = "Gestion")
	private Short gestion;
	
	@Column(name = "Num", nullable = false)
	private short num;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Journee", length = 23)
	private Date journee;
	
	@Column(name = "Total", precision = 18, scale = 0)
	private Long total;
	
	@Column(name = "TotalAnterieur", precision = 18, scale = 0)
	private Long totalAnterieur;
	
	@Column(name = "TotalCumul", precision = 18, scale = 0)
	private Long totalCumul;
	
	@Column(name = "IdLogin", nullable = false, length = 5)
	private String idLogin;
	
	@Column(name = "Dossier", nullable = false, length = 1)
	private String dossier;
	
	@Column(name = "Actif", nullable = false)
	private boolean actif;
	
	@Column(name = "MontDeduit", nullable = false, precision = 18, scale = 0)
	private long montDeduit;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateReception", length = 23)
	private Date dateReception;
	
	@Column(name = "UserReception", length = 5)
	private String userReception;
	
	@Column(name = "IdentiteRecept", length = 150)
	private String identiteRecept;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bordereauEmismandats")
	private List<Mandats> mandats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bordereauEmismandats")
	private List<BordTitre> bordTitres = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bordereauEmismandats")
	private List<BordMand> bordMands = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bordereauEmismandats")
	private List<TitreDetail> titreDetails = new ArrayList<>();

	public BordereauEmismandats(Short gestion, short num, Date journee, Long total, Long totalAnterieur,
			Long totalCumul, String idLogin, String dossier, boolean actif, long montDeduit, Date dateReception,
			String userReception, String identiteRecept, BudgetType budgetType, List<Mandats> mandats,
			List<BordTitre> bordTitres, List<BordMand> bordMands, List<TitreDetail> titreDetails) {
		super();
		this.gestion = gestion;
		this.num = num;
		this.journee = journee;
		this.total = total;
		this.totalAnterieur = totalAnterieur;
		this.totalCumul = totalCumul;
		this.idLogin = idLogin;
		this.dossier = dossier;
		this.actif = actif;
		this.montDeduit = montDeduit;
		this.dateReception = dateReception;
		this.userReception = userReception;
		this.identiteRecept = identiteRecept;
		this.budgetType = budgetType;
		this.mandats = mandats;
		this.bordTitres = bordTitres;
		this.bordMands = bordMands;
		this.titreDetails = titreDetails;
	}
}
