package com.sigep.gbc.entity;
// Generated 24 ao�t 2022, 13:59:44 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BudgetType generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BudgetType")
public class BudgetType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdBudget", unique = true, nullable = false)
	private Integer idBudget;
	
	@Column(name = "LibelleBudget", nullable = false, length = 150)
	private String libelleBudget;
	
	@Column(name = "LibelleDecision", nullable = false, length = 250)
	private String libelleDecision;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<BudgetTypeGestion> budgetTypeGestions = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<Budget> budgets = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<BordTransmis> bordTransmiss = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<BordereauEmismandats> bordereauEmismandatss = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<TitreDetail> titreDetails = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<PpmActe> ppmActes = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<Ppm> ppms = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<Contrats> contrats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<Engagements> engagements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<Mandats> mandats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<Decision> decisions = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<CompteMouvement> compteMouvements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<ReportAnouveau> reportAnouveaus = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetType")
	private List<RetenuTitreRecouv> retenuTitreRecouvs = new ArrayList<>();
}
