package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BudgetModif generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BudgetModif", schema = "dbo")
public class BudgetModif implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codBma", column = @Column(name = "CodBMA", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "codBud", column = @Column(name = "CodBud", nullable = false)) })
	private BudgetModifId id;
	
	@Column(name = "Ajoute", precision = 18, scale = 0)
	private Long ajoute;

	@Column(name = "Annule", precision = 18, scale = 0)
	private Long annule;
	
	@Column(name = "Nouvelle", nullable = false)
	private boolean nouvelle;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBMA", nullable = false, insertable = false, updatable = false)
	private BudgetModifActe budgetModifActe;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false, insertable=false, updatable=false)
	private Budget budget;
}
