package com.sigep.gbc.entity;
// Generated 24 ao�t 2022, 13:59:44 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BudgetTypeGestionId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class BudgetTypeGestionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "IdBudget", nullable = false)
	private int idBudget;
	
	@Column(name = "Annee", nullable = false)
	private short annee;

}
