package com.sigep.gbc.entity;
// Generated 24 ao�t 2022, 13:59:44 by Hibernate Tools 4.3.6.Final


import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Budget generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Budget")
public class Budget implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "CodBud", unique = true, nullable = false)
	private String codBud;
	
	@Column(name = "Intitule")
	private String intitule;
	
	@Column(name = "DotInitiale", nullable = false, precision = 18, scale = 0)
	private long dotInitiale;
	
	@Column(name = "CAajout", nullable = false, precision = 18, scale = 0)
	private long caajout;
	
	@Column(name = "CAannul", nullable = false, precision = 18, scale = 0)
	private long caannul;
	
	@Column(name = "Ream", nullable = false, precision = 18, scale = 0)
	private long ream;
	
	@Column(name = "TotalEngag", precision = 18, scale = 0)
	private long totalEngag;
	
	@Column(name = "DotN1", precision = 18, scale = 0)
	private Long dotN1;
	
	@Column(name = "ExecN1", precision = 18, scale = 0)
	private Long execN1;
	
	@Column(name = "DotN2", precision = 18, scale = 0)
	private Long dotN2;
	
	@Column(name = "ExecN2", precision = 18, scale = 0)
	private Long execN2;
	
	@Column(name = "DotN3", precision = 18, scale = 0)
	private Long dotN3;
	
	@Column(name = "ExecN3", precision = 18, scale = 0)
	private Long execN3;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false)
	private Gestion gestion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumNo", nullable = false)
	private NomenclatureD nomenclatureD;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPlan", nullable = false)
	private PlanComptable planComptable;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<TitreDetail> titreDetails = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<TitreEmis> titreEmis = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<PpmBudg> ppmBudgs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<Engagements> engagements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<Mandats> mandats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<ReportDetail> reportDetails = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<RetenuTitreRecouv> retenuTitreRecouvs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<BudgetModif> budgetModifs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budget")
	private List<Reamgmt> reamgmts = new ArrayList<>();
	
	
}
