package com.sigep.gbc.entity;
// Generated 24 ao�t 2022, 13:59:44 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BudgetTypeGestion generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BudgetTypeGestion")
public class BudgetTypeGestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idBudget", column = @Column(name = "IdBudget", nullable = false)),
			@AttributeOverride(name = "annee", column = @Column(name = "Annee", nullable = false)) })
	private BudgetTypeGestionId id;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateMiseEnPlace", length = 23)
	private Date dateMiseEnPlace;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCloture", length = 23)
	private Date dateCloture;
	
	@Column(name = "Fermer", nullable = false)
	private boolean fermer;
	
	@Column(name = "PageCommencantA", nullable = false)
	private int pageCommencantA;
	
	@Column(name = "EteteD", length = 250)
	private String eteteD;
	
	@Column(name = "EteteM", length = 250)
	private String eteteM;
	
	@Column(name = "PiedD", length = 250)
	private String piedD;
	
	@Column(name = "PiedM", length = 250)
	private String piedM;
	
	@Column(name = "SignataireBud", length = 250)
	private String signataireBud;
	
	@Column(name = "NomSignataire", length = 250)
	private String nomSignataire;
	
	@Column(name = "HonoSignataire", length = 250)
	private String honoSignataire;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false, insertable = false, updatable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Annee", nullable = false, insertable = false, updatable = false)
	private Gestion gestion;
}
