package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BudgetModifActe generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BudgetModifActe", schema = "dbo")
public class BudgetModifActe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CodBMA", unique = true, nullable = false, precision = 18, scale = 0)
	private long codBma;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSaisie", nullable = false, length = 23)
	private Date dateSaisie;
	
	@Column(name = "Valide", nullable = false)
	private boolean valide;
	
	@Column(name = "ActeBMA", nullable = false)
	private String acteBma;
	
	@Column(name = "NumActeBMA", nullable = false)
	private String numActeBma;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateActeBMA", length = 16)
	private Date dateActeBma;
	
	@Column(name = "IdLogin", nullable = false, length = 5)
	private String idLogin;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateValid", length = 23)
	private Date dateValid;

	@Column(name = "IdValid", length = 5)
	private String idValid;

	@Column(name = "IdBudget", nullable = false)
	private int idBudget;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetModifActe")
	private List<BudgetModif> budgetModifs = new ArrayList<>();
}
