package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CaisseSession generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "CaisseSession", schema = "dbo")
public class CaisseSession implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdSession", unique = true, nullable = false, length = 36)
	private String idSession;
	
	@Column(name = "IdBudget", nullable = false)
	private int idBudget;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSession", nullable = false, length = 23)
	private Date dateSession;
	
	@Column(name = "QuantSession", nullable = false)
	private int quantSession;
	
	@Column(name = "MonnaieEntre", nullable = false, precision = 53, scale = 0)
	private double monnaieEntre;
	
	@Column(name = "MontantSession", nullable = false, precision = 53, scale = 0)
	private double montantSession;
	
	@Column(name = "MontTotalSession", nullable = false, precision = 53, scale = 0)
	private double montTotalSession;
	
	@Column(name = "SesionFermee", nullable = false)
	private boolean sesionFermee;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateFermee", length = 23)
	private Date dateFermee;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserName", nullable = false)
	private AccesCode accesCode;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caisseSession")
	private List<CaisseSessionBilletage> caisseSessionBilletages = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caisseSession")
	private List<CompteMouvement> compteMouvements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caisseSession")
	private List<CaisseSessionVente> caisseSessionVentes = new ArrayList<>();

	public CaisseSession(int idBudget, Date dateSession, int quantSession, double monnaieEntre, double montantSession,
			double montTotalSession, boolean sesionFermee, Date dateFermee, AccesCode accesCode,
			List<CaisseSessionBilletage> caisseSessionBilletages, List<CompteMouvement> compteMouvements,
			List<CaisseSessionVente> caisseSessionVentes) {
		super();
		this.idBudget = idBudget;
		this.dateSession = dateSession;
		this.quantSession = quantSession;
		this.monnaieEntre = monnaieEntre;
		this.montantSession = montantSession;
		this.montTotalSession = montTotalSession;
		this.sesionFermee = sesionFermee;
		this.dateFermee = dateFermee;
		this.accesCode = accesCode;
		this.caisseSessionBilletages = caisseSessionBilletages;
		this.compteMouvements = compteMouvements;
		this.caisseSessionVentes = caisseSessionVentes;
	}
}
