package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CaisseSessionVente generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "CaisseSessionVente", schema = "dbo")
public class CaisseSessionVente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdVente", unique = true, nullable = false, length = 36)
	private String idVente;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateVente", nullable = false, length = 23)
	private Date dateVente;
	
	@Column(name = "MontantRemis", nullable = false, precision = 18, scale = 0)
	private long montantRemis;
	
	@Column(name = "MontantVente", nullable = false, precision = 18, scale = 0)
	private long montantVente;
	
	@Column(name = "AGenerer", nullable = false)
	private boolean agenerer;
	
	@Column(name = "QuantiemeAn", nullable = false, precision = 18, scale = 0)
	private long quantiemeAn;
	
	@Column(name = "RefQuittance")
	private String refQuittance;
	

	@Column(name = "QR_code")
	private byte[] qrCode;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateE", nullable = false, length = 23)
	private Date dateE;

	@Column(name = "IdentiteVersant")
	private String identiteVersant;
	
	@Column(name = "IdCpteCredit", nullable = false)
	private String idCpteCredit;
	
	@Column(name = "IdPlan", nullable = false)
	private String idPlan;

	@Column(name = "IdDest", nullable = false, precision = 18, scale = 0)
	private long idDest;

	@Column(name = "IdCaisse", nullable = false)
	private String idCaisse;

	@Column(name = "PrenomNomSigna")
	private String prenomNomSigna;
	
	@Column(name = "IdModePaie", nullable = false, length = 3)
	private String idModePaie;
	
	@Column(name = "Annule", nullable = false)
	private boolean annule;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSession", nullable = false)
	private CaisseSession caisseSession;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdEltR", nullable = false)
	private EtatVersementElts etatVersementElts;

	public CaisseSessionVente(Date dateVente, long montantRemis, long montantVente, boolean agenerer, long quantiemeAn,
			String refQuittance, byte[] qrCode, Date dateE, String identiteVersant, String idCpteCredit, String idPlan,
			long idDest, String idCaisse, String prenomNomSigna, String idModePaie, boolean annule,
			CaisseSession caisseSession, EtatVersementElts etatVersementElts) {
		super();
		this.dateVente = dateVente;
		this.montantRemis = montantRemis;
		this.montantVente = montantVente;
		this.agenerer = agenerer;
		this.quantiemeAn = quantiemeAn;
		this.refQuittance = refQuittance;
		this.qrCode = qrCode;
		this.dateE = dateE;
		this.identiteVersant = identiteVersant;
		this.idCpteCredit = idCpteCredit;
		this.idPlan = idPlan;
		this.idDest = idDest;
		this.idCaisse = idCaisse;
		this.prenomNomSigna = prenomNomSigna;
		this.idModePaie = idModePaie;
		this.annule = annule;
		this.caisseSession = caisseSession;
		this.etatVersementElts = etatVersementElts;
	}
}
