package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ChequesVirements generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ChequesVirements", schema = "dbo")
public class ChequesVirements implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numMand", column = @Column(name = "NumMand", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "chqVirNum", column = @Column(name = "ChqVirNum", nullable = false)) })
	private ChequesVirementsId id;
	
	@Column(name = "MontantChqVir", nullable = false, precision = 18, scale = 0)
	private long montantChqVir;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePosiChqVir", length = 16)
	private Date datePosiChqVir;

	@Column(name = "NatureChqVir", length = 3)
	private String natureChqVir;

	@Column(name = "mleSignataire1")
	private Integer mleSignataire1;

	@Column(name = "mleSignataire2")
	private Integer mleSignataire2;

	@Column(name = "mleSignataire3")
	private Integer mleSignataire3;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand", nullable = false, insertable = false, updatable = false)
	private Mandats mandats;
}
