package com.sigep.gbc.entity;
// Generated 27 juin 2022, 18:53:35 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CircuitGrh generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CircuitGRHS")
public class CircuitGrh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	private int idCircuitGrh;
	
	@Column(name = "descriptionCircuit", nullable = false, length = 450)
	private String descriptionCircuit;
}
