package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CodModPass generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CodModPass", schema = "dbo")
public class CodModPass implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "Cod4", unique = true, nullable = false)
	private String cod4;
	
	@Column(name = "Intitule")
	private String intitule;
	
	@Column(name = "LibelleCourt", nullable = false, length = 50)
	private String libelleCourt;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdProc", nullable = false)
	private PpmProcedure ppmProcedure;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codModPass")
	private List<PpmModePass> ppmModePasss = new ArrayList<>();
}
