package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CompteMouvTypOp generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CompteMouvTypOp", schema = "dbo")
public class CompteMouvTypOp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "TypeOp", unique = true, nullable = false)
	private String typeOp;
	
	@Column(name = "LibelleOP", nullable = false, length = 50)
	private String libelleOp;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteMouvTypOp")
	private List<CompteMouvement> compteMouvements = new ArrayList<>();
}
