package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CompteDestinataire generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "CompteDestinataire", schema = "dbo")
public class CompteDestinataire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false, length = 36)
	private String id;
	
	@Column(name = "CodeBanque", nullable = false)
	private String codeBanque;
	
	@Column(name = "CodeAgence", nullable = false)
	private String codeAgence;
	
	@Column(name = "NumCompte", nullable = false)
	private String numCompte;
	
	@Column(name = "CleRIB", nullable = false)
	private String cleRib;
	
	@Column(name = "CaissePop")
	private String caissePop;
	
	@Column(name = "numCaissePop")
	private String numCaissePop;
	
	@Column(name = "CodeBIC", length = 50)
	private String codeBic;
	
	@Column(name = "IBAN", length = 50)
	private String iban;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCaissePop")
	private TiersCaissePop tiersCaissePop;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDest", nullable = false)
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Abreviation", nullable = false)
	InstitutFinancier institutFinancier;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdAgence", nullable = false)
	InstitutFinAgence institutFinAgence;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteDestinataire")
	private List<Liquidation> liquidations = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteDestinataire")
	private List<Mandats> mandats = new ArrayList<>();

	public CompteDestinataire(String codeBanque, String codeAgence, String numCompte, String cleRib, String caissePop,
			String numCaissePop, String codeBic, String iban, TiersCaissePop tiersCaissePop,
			Destinataires destinataires, InstitutFinancier institutFinancier, InstitutFinAgence institutFinAgence,
			List<Liquidation> liquidations, List<Mandats> mandats) {
		super();
		this.codeBanque = codeBanque;
		this.codeAgence = codeAgence;
		this.numCompte = numCompte;
		this.cleRib = cleRib;
		this.caissePop = caissePop;
		this.numCaissePop = numCaissePop;
		this.codeBic = codeBic;
		this.iban = iban;
		this.tiersCaissePop = tiersCaissePop;
		this.destinataires = destinataires;
		this.institutFinancier = institutFinancier;
		this.institutFinAgence = institutFinAgence;
		this.liquidations = liquidations;
		this.mandats = mandats;
	}
}
