package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CompteMouvementMandR generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "CompteMouvementMandR", schema = "dbo")
public class CompteMouvementMandR implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "compteMouvement"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdBord", unique = true, nullable = false, precision = 18, scale = 0)
	private long idBord;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private CompteMouvement compteMouvement;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand", nullable = false)
	private Mandats mandats;

	public CompteMouvementMandR(CompteMouvement compteMouvement, Mandats mandats) {
		super();
		this.compteMouvement = compteMouvement;
		this.mandats = mandats;
	}
}
