package com.sigep.gbc.entity;
// Generated 23 nov. 2022, 13:29:31 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Compte generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Compte")
public class Compte implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "CodCpte", unique = true, nullable = false)
    private String codCpte;
    
    @Column(name = "NumCompte")
    private String numCompte;
    
    @Column(name = "Intitule")
    private String intitule;
    
    @Column(name = "Attente")
    private Boolean attente;
    
    @Column(name = "Abreviation", length = 20)
    private String abreviation;
    
    @Column(name = "CodeBanque")
    private String codeBanque;
    
    @Column(name = "CodeAgence")
    private String codeAgence;
    
    @Column(name = "CleRIB")
    private String cleRib;
    
    @Column(name = "CaissePop")
    private String caissePop;
    
    @Column(name = "numCaissePop")
    private String numCaissePop;
    
    @Column(name = "Solde", nullable = false, precision = 18, scale = 0)
    private long solde;
    
    @Column(name = "LibCompte", nullable = false)
    private String libCompte;
    
    @OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private PlanComptable planComptable;
    
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retenueCategorie")
	private List<RetenuType> retenuTypes = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<Factures> facturess = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<TitreEmis> titreEmis = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<MandatLettragPaie> mandatLettragPaies = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<CompteMouvement> compteMouvements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<ReportCompte> reportComptes = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<RetenuTitreRecouv> retenuTitreRecouvs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<CompteMouvDebit> compteMouvDebits = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<PaiementCpte> paiementCptes = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compte")
	private List<MandatPec> mandatPecs = new ArrayList<>();
}
