package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CompteMouvQuit generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "CompteMouv_Quit", schema = "dbo")
public class CompteMouvQuit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "compteMouvement"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdBord", unique = true, nullable = false, precision = 18, scale = 0)
	private long idBord;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreat", nullable = false, length = 23)
	private Date dateCreat;
	
	@Column(name = "QR_code")
	private byte[] qrCode;

	@Column(name = "QuantiemeAn", nullable = false, precision = 18, scale = 0)
	private long quantiemeAn;

	@Column(name = "RefQuittance", nullable = false)
	private String refQuittance;

	@Column(name = "IdBudget", nullable = false)
	private int idBudget;

	@Column(name = "ID", length = 36)
	private String id;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private CompteMouvement compteMouvement;

	public CompteMouvQuit(Date dateCreat, byte[] qrCode, long quantiemeAn, String refQuittance, int idBudget, String id,
			CompteMouvement compteMouvement) {
		super();
		this.dateCreat = dateCreat;
		this.qrCode = qrCode;
		this.quantiemeAn = quantiemeAn;
		this.refQuittance = refQuittance;
		this.idBudget = idBudget;
		this.id = id;
		this.compteMouvement = compteMouvement;
	}
}
