package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CompteMouvement generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CompteMouvement", schema = "dbo")
public class CompteMouvement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdBord", unique = true, nullable = false, precision = 18, scale = 0)
	private long idBord;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreat", nullable = false, length = 16)
	private Date dateCreat;
	
	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;
	
	@Column(name = "Numero", nullable = false)
	private int numero;

	@Column(name = "Libelle", nullable = false)
	private String libelle;

	@Column(name = "Versant")
	private String versant;

	@Column(name = "RefActe")
	private String refActe;

	@Column(name = "IdLogin", nullable = false, length = 5)
	private String idLogin;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePosition", length = 16)
	private Date datePosition;
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEtat", nullable = false, length = 23)
	private Date dateEtat;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "ModeDate", length = 10)
	private Date modeDate;

	@Column(name = "mleSignataire1")
	private Integer mleSignataire1;

	@Column(name = "mleSignataire2")
	private Integer mleSignataire2;

	@Column(name = "mleSignataire3")
	private Integer mleSignataire3;

	@Column(name = "Ref")
	private String ref;

	@Column(name = "Periode")
	private Integer periode;
	
	@Column(name = "TypePeriode", length = 50)
	private String typePeriode;

	@Column(name = "IdCategorie")
	private String idCategorie;

	@Column(name = "GenererOV", nullable = false)
	private boolean genererOv;

	@Column(name = "EstReversement", nullable = false)
	private boolean estReversement;

	@Column(name = "EstVersement", nullable = false)
	private boolean estVersement;

	@Column(name = "GenererQuit", nullable = false)
	private boolean genererQuit;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSession")
	private CaisseSession caisseSession;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Type", nullable = false)
	private CompteMouvTypOp compteMouvTypOp;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Etat", nullable = false)
	private EtatDossier etatDossier;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mode", nullable = false)
	private ModePaiement modePaiement;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false)
	private Gestion gestion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCpteCredit", nullable = false)
	private Compte compte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDest", nullable = false)
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteMouvement")
	private List<CompteMouvBilletage> compteMouvBilletages = new ArrayList<>();
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "compteMouvement")
	private CompteMouvQuit compteMouvQuit;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteMouvement")
	private List<CompteMouvDebit> compteMouvDebits = new ArrayList<>();
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "compteMouvement")
	private CompteMouvementMandR compteMouvementMandR;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteMouvement")
	private List<JournalPiece> journalPieces = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteMouvement")
	private List<CompteMouvRetenu> compteMouvRetenus = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteMouvement")
	private List<CompteMouvEtatVelts> compteMouvEtatVelts = new ArrayList<>();
}
