package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CompteMouvEtatVelts generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CompteMouv_EtatVElts", schema = "dbo")
public class CompteMouvEtatVelts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idBord", column = @Column(name = "IdBord", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "idEltR", column = @Column(name = "IdEltR", nullable = false)) })
	private CompteMouvEtatVeltsId id;
	
	@Column(name = "MontantElts", nullable = false, precision = 18, scale = 0)
	private long montantElts;

	@Column(name = "IdPlan")
	private String idPlan;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBord", nullable = false, insertable = false, updatable = false)
	private CompteMouvement compteMouvement;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdEltR", nullable = false, insertable = false, updatable = false)
	private EtatVersementElts etatVersementElts;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodRecouv")
	private Recouvrements recouvrements;
}
