package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CompteMouvDebit generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CompteMouvDebit", schema = "dbo")
public class CompteMouvDebit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idBord", column = @Column(name = "IdBord", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "idCptRep", column = @Column(name = "IdCptRep", nullable = false)) })
	private CompteMouvDebitId id;
	
	@Column(name = "Debiter", precision = 18, scale = 0)
	private Long debiter;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBord", nullable = false, insertable = false, updatable = false)
	private CompteMouvement compteMouvement;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCptRep", nullable = false, insertable = false, updatable = false)
	private Compte compte;
}
