package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.annotation.ReadOnlyProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Contrats generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Contrats", schema = "dbo")
public class Contrats implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdContrat", unique = true, nullable = false, precision = 18, scale = 0)
	private long idContrat;
	
	@Column(name = "Cod1")
	private String cod1;
	
	@Column(name = "Cod2")
	private String cod2;
	
	@Column(name = "Cod3")
	private String cod3;
	
	@Column(name = "Cod4")
	private String cod4;
	
	@Column(name = "Cod5")
	private String cod5;
	
	@Column(name = "annee", nullable = false)
	private short annee;
	
	@Column(name = "Numero")
	private Integer numero;
	
	@Column(name = "Objet", nullable = false)
	private String objet;
	
	@Column(name = "Reference")
	private String reference;
	
	@Column(name = "DelaiNbre", nullable = false, precision = 18, scale = 0)
	private long delaiNbre;
	
	@Column(name = "DelaiText", nullable = false)
	private String delaiText;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSaisie", length = 23)
	private Date dateSaisie;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateApprob", length = 10)
	private Date dateApprob;
	
	@Column(name = "ActeRef")
	private String acteRef;
	
	@Column(name = "RefNotif")
	private String refNotif;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateNotif", length = 16)
	private Date dateNotif;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateDemmar", length = 16)
	private Date dateDemmar;
	
	@Column(name = "MleAuto", nullable = false)
	private boolean mleAuto;
	
	@Column(name = "RefPassation", length = 150)
	private String refPassation;
	
	@Column(name = "RefArt")
	private String refArt;
	
	@Column(name = "Tauxappli", precision = 18)
	private BigDecimal tauxappli;
	
	@Column(name = "Suspens")
	private Boolean suspens;
	
	@Column(name = "IdLogin", nullable = false, length = 5)
	private String idLogin;
	
	@Column(name = "Idcompte", length = 36)
	private String idcompte;
	
	@Column(name = "Avenant", nullable = false, precision = 18, scale = 0)
	private long avenant;
	
	@Column(name = "Degage", nullable = false, precision = 18, scale = 0)
	private long degage;
	
	@Column(name = "Engage", nullable = false, precision = 18, scale = 0)
	private long engage;

	@Column(name = "Mandate", nullable = false, precision = 18, scale = 0)
	private long mandate;
	
	@Column(name = "Paie", nullable = false, precision = 18, scale = 0)
	private long paie;
	
	@Column(name = "EngageValid", nullable = false, precision = 18, scale = 0)
	private long engageValid;
	
	@Column(name = "MandateValid", nullable = false, precision = 18, scale = 0)
	private long mandateValid;
	
	@Column(name = "MontantMaxHTVA", nullable = false, precision = 18, scale = 0)
	private long montantMaxHtva;
	
	@Column(name = "MontantMinHTVA", nullable = false, precision = 18, scale = 0)
	private long montantMinHtva;
	
	@Column(name = "MontantMaxTTC", nullable = false, precision = 18, scale = 0)
	private long montantMaxTtc;

	@Column(name = "MontantMinTTC", nullable = false, precision = 18, scale = 0)
	private long montantMinTtc;
	
	@Column(name = "AvecTVA", nullable = false)
	private boolean avecTva;
	
	@Column(name = "AvecMiniMax", nullable = false)
	private boolean avecMiniMax;
	
	@ReadOnlyProperty
	@Column(name = "Montant", nullable = false, precision = 18, scale = 0, insertable = false, updatable = false)
	private long montant;
	
	@ReadOnlyProperty
	@Column(name = "MontantCorrige", scale = 0, insertable = false, updatable = false)
	private BigInteger montantCorrige;
	
	@Column(name = "DelaiAn", nullable = false)
	private int delaiAn;
	
	@Column(name = "DelaiMois", nullable = false)
	private int delaiMois;
	
	@Column(name = "DelaiSemaine", nullable = false)
	private int delaiSemaine;
	
	@Column(name = "DelaiJours", nullable = false)
	private int delaiJours;

	@ReadOnlyProperty
	@Column(name = "DelaiEnJours", insertable = false, updatable = false)
	private Integer delaiEnJours;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreate", nullable = false, length = 23)
	private Date dateCreate;
	
	@Column(name = "UserUpdate", nullable = false, length = 10)
	private String userUpdate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateUpdate", nullable = false, length = 23)
	private Date dateUpdate;
	
	@Column(name = "IdContratParent", length = 128)
	private String idContratParent;
	
	@Column(name = "AbrevEpe", nullable = false)
	private String abrevEpe;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateAttribution", nullable = false, length = 10)
	private Date dateAttribution;
	
	@Column(name = "CodTypeMarche")
	private String codTypeMarche;
	
	@Column(name = "CodIdentiteExecution")
	private String codIdentiteExecution;
	
	@Column(name = "IdPPMExe") // PPM EXEC BUDG CLE S'AJOUTE GESTION ET IDBUDGET
    private Integer idPpmExe;
	
	@Column(name = "IdLot")
    private Integer idLot;
	
	@Column(name = "CodBud")
    private String codBud;
    
    @Column(name = "IdSrceFin") // PPM EXEC BUDG CLE S'AJOUTE GESTION ET IDBUDGET
    private String idSrceFin;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Type", nullable = false)
	private ContratType contratType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFourn", nullable = false)
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDAC")
	private PpmDac ppmDac;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrats")
	private List<Liquidation> liquidations = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrats")
	private List<Livraisons> livraisons = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrats")
	private List<Penalite> penalites = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrats")
	private List<Suspension> suspensions = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrats")
	private List<Avenant> avenants = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrats")
	private List<Retenus> retenus = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrats")
	private List<Engagements> engagements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrats")
	private List<Mandats> mandats = new ArrayList<>();
}
