package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ContratType generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ContratType", schema = "dbo")
public class ContratType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "TypeContrat", unique = true, nullable = false)
	private String typeContrat;
	
	@Column(name = "Libelle")
	private String libelle;
	
	@Column(name = "AvecMiniMax", nullable = false)
	private boolean avecMiniMax;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contratType")
	private List<Contrats> contrats = new ArrayList<>();
}
