package com.sigep.gbc.entity;
// Generated 6 d�c. 2022, 11:35:43 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CoupureMonnaieId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class CoupureMonnaieId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "Designa", nullable = false, length = 1)
	private String designa;
	
	@Column(name = "IdCoupure", nullable = false, precision = 18, scale = 0)
	private long idCoupure;
}
