package com.sigep.gbc.entity;
// Generated 6 d�c. 2022, 11:35:43 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CoupureMonnaie generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "CoupureMonnaie")
public class CoupureMonnaie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "designa", column = @Column(name = "Designa", nullable = false, length = 1)),
			@AttributeOverride(name = "idCoupure", column = @Column(name = "IdCoupure", nullable = false, precision = 18, scale = 0)) })
	private CoupureMonnaieId id;
}
