package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DebiteurEleve generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "DebiteurEleve", schema = "Elev")
public class DebiteurEleve implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdDebiteur", unique = true, nullable = false, precision = 18, scale = 0)
	private long idDebiteur;
	
	@Column(name = "NomEleve", nullable = false, length = 50)
	private String nomEleve;
	
	@Column(name = "PrenomEleve", nullable = false, length = 50)
	private String prenomEleve;

	@Column(name = "SexeEleve", nullable = false, length = 1)
	private char sexeEleve;

	@Column(name = "NomDebiteur", nullable = false, length = 101)
	private String nomDebiteur;

	@Column(name = "AdresseEleve", length = 250)
	private String adresseEleve;

	@Column(name = "TelEleve")
	private String telEleve;

	@Column(name = "EmailEleve")
	private String emailEleve;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdTypElev", nullable = false)
	private EleveType eleveType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Destinataires destinataires;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "debiteurEleve")
	private List<InscritPour> inscritPours = new ArrayList<>();
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "debiteurEleve")
	private InfoInscriptionEleve infoInscriptionEleve;
}
