package com.sigep.gbc.entity;
// Generated 31 janv. 2023, 14:11:42 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DecisionSampliation generated by hbm2java
 */

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "DecisionSAmpliation")
public class DecisionSampliation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "Ampliataire", length = 50)
	private String ampliataire;
	
	@Column(name = "AmpliataireReam", length = 50)
	private String ampliataireReam;
}
