package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Decision generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Decision", schema = "dbo")
public class Decision implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdDecision", unique = true, nullable = false, length = 36)
	private String idDecision;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", length = 23)
	private Date dateCreation;
	
	@Column(name = "NumChrono", nullable = false)
	private int numChrono;
	
	@Column(name = "Signataire", nullable = false)
	private String signataire;
	
	@Column(name = "PrenomNomSignataire", nullable = false, length = 510)
	private String prenomNomSignataire;
	
	@Column(name = "TitreHonoSignataire", nullable = false)
	private String titreHonoSignataire;
	

	@Column(name = "NumDecision", nullable = false, length = 250)
	private String numDecision;
	

	@Column(name = "TitreStructure", nullable = false, length = 650)
	private String titreStructure;
	
	@Column(name = "ActeAn", nullable = false)
	private short acteAn;

	@Column(name = "ActeNumComplema", nullable = false, length = 50)
	private String acteNumComplema;

	@Column(name = "ComplemaVisa", nullable = false, length = 5)
	private String complemaVisa;

	@Column(name = "ComplemaVisaLib", nullable = false)
	private String complemaVisaLib;

	@Column(name = "Objet", nullable = false, length = 850)
	private String objet;

	@Column(name = "TitreDecision", nullable = false, length = 500)
	private String titreDecision;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreat", nullable = false, length = 23)
	private Date dateCreat;

	@Column(name = "Auprofit", nullable = false, length = 500)
	private String auprofit;

	@Column(name = "NomJustif", nullable = false, length = 500)
	private String nomJustif;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumBE", nullable = false)
	private Engagements engagements;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decision")
	private List<DecisionHvisa> decisionHvisas = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decision")
	private List<DecisionHampliation> decisionHampliations = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decision")
	private List<DecisionHarticle> decisionHarticles = new ArrayList<>();

	public Decision(Date dateCreation, int numChrono, String signataire, String prenomNomSignataire,
			String titreHonoSignataire, String numDecision, String titreStructure, short acteAn, String acteNumComplema,
			String complemaVisa, String complemaVisaLib, String objet, String titreDecision, Date dateCreat,
			String auprofit, String nomJustif, Engagements engagements, BudgetType budgetType,
			List<DecisionHvisa> decisionHvisas, List<DecisionHampliation> decisionHampliations,
			List<DecisionHarticle> decisionHarticles) {
		super();
		this.dateCreation = dateCreation;
		this.numChrono = numChrono;
		this.signataire = signataire;
		this.prenomNomSignataire = prenomNomSignataire;
		this.titreHonoSignataire = titreHonoSignataire;
		this.numDecision = numDecision;
		this.titreStructure = titreStructure;
		this.acteAn = acteAn;
		this.acteNumComplema = acteNumComplema;
		this.complemaVisa = complemaVisa;
		this.complemaVisaLib = complemaVisaLib;
		this.objet = objet;
		this.titreDecision = titreDecision;
		this.dateCreat = dateCreat;
		this.auprofit = auprofit;
		this.nomJustif = nomJustif;
		this.engagements = engagements;
		this.budgetType = budgetType;
		this.decisionHvisas = decisionHvisas;
		this.decisionHampliations = decisionHampliations;
		this.decisionHarticles = decisionHarticles;
	}
}
