package com.sigep.gbc.entity;
// Generated 31 janv. 2023, 14:11:42 by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DecisionSvisa generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "DecisionSVisa")
public class DecisionSvisa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "RangVisa", unique = true, nullable = false)
	private int rangVisa;
	
	@Column(name = "LibelleVisa", nullable = false, length = 650)
	private String libelleVisa;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdType", nullable = false)
	private TypeDecision typeDecision;
}
