package com.sigep.gbc.entity;
// Generated 31 janv. 2023, 14:11:42 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DecisionSarticle generated by hbm2java
 */

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "DecisionSArticle")
public class DecisionSarticle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "numArticle", unique = true, nullable = false)
	private int numArticle;
	
	@Column(name = "IntituleArticle", length = 650)
	private String intituleArticle;
	
	@Column(name = "IntituleArticleReam", length = 650)
	private String intituleArticleReam;
}
