package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DecisionHampliation generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "DecisionHAmpliation", schema = "dbo")
public class DecisionHampliation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDecision", column = @Column(name = "IdDecision", nullable = false, length = 36)),
			@AttributeOverride(name = "ampliataire", column = @Column(name = "Ampliataire", nullable = false, length = 50)) })
	private DecisionHampliationId id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDecision", nullable = false, insertable = false, updatable = false)
	private Decision decision;
}
