package com.sigep.gbc.entity;
// Generated 28 juin 2022, 18:45:14 by Hibernate Tools 4.3.6.Final


import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Destinataires generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Destinataires")
public class Destinataires implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdDest")
	private long idDest;
	
	@Column(name = "IFUMle", length = 50)
	private String ifumle;
	
	@Column(name = "fType", nullable = false, length = 1)
	private String ftype;
	
	@Column(name = "ContactTel", length = 150)
	private String contactTel;
	
	@Column(name = "ContactEmail", length = 150)
	private String contactEmail;
	
	@Column(name = "Nom", length = 300)
	private String nom;
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private Agents agents;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<Factures> facturess = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<TitreEmis> titreEmis = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<Contrats> contrats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<Engagements> engagements = new ArrayList<>();
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private TiersCaissePop tiersCaissePop;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<CompteDestinataire> compteDestinataires = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<MandatLettragPaie> mandatLettragPaies = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<Mandats> mandats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<EtatVersementElts> etatVersementElts = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<CompteMouvement> compteMouvements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<RetenuTitreRecouv> retenuTitreRecouvs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<Retenus> retenus = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinataires")
	private List<DebiteurEleve> debiteurEleves = new ArrayList<>();
}
