package com.sigep.gbc.entity;
// Generated 28 juin 2022, 17:07:22 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DirectionServiceNiveau generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "DirectionServiceNiveauS")
public class DirectionServiceNiveau implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	private int idNiveau;
	
	@Column(name = "libelleNiveau", nullable = false, length = 150)
	private String libelleNiveau;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "directionServiceNiveau")
	private List<DirectionService> directionServices = new ArrayList<>();
	
	
	
	public void addDirectionService(DirectionService directionService) {
		directionServices.add(directionService);
	}
	
	public void removeDirectionService(DirectionService directionService) {
		directionServices.remove(directionService);
	}
}
