package com.sigep.gbc.entity;
// Generated 28 juin 2022, 17:07:22 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Organigramme generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "DirectionServiceS")
public class DirectionService implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idService;
	
	@Column(name = "libelle", nullable = false, length = 250)
	private String libelle;
	
	@Column(name = "abrev", length = 10)
	private String abrev;
	
	@Column(name = "idHerachique", nullable = false, length = 150)
	private String idHerachique;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idNiveau", nullable = false)
	private DirectionServiceNiveau directionServiceNiveau;
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codStruct", nullable = false)
	private EnteteStructure enteteStructure;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idParent")
	private DirectionService directionService;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "directionService")
	private List<DirectionService> directionServices = new ArrayList<>();

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "directionService")
	private List<Agents> agents = new ArrayList<>();

	public DirectionService(String libelle, String abrev, String idHerachique,
			DirectionServiceNiveau directionServiceNiveau, EnteteStructure enteteStructure,
			DirectionService directionService, List<DirectionService> directionServices, List<Agents> agents) {
		super();
		this.libelle = libelle;
		this.abrev = abrev;
		this.idHerachique = idHerachique;
		this.directionServiceNiveau = directionServiceNiveau;
		this.enteteStructure = enteteStructure;
		this.directionService = directionService;
		this.directionServices = directionServices;
		this.agents = agents;
	}
}
