package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Engagements generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Engagements", schema = "dbo")
public class Engagements implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "NumBE", unique = true, nullable = false, precision = 18, scale = 0)
	private long numBe;
	
	@Column(name = "BENum", nullable = false)
	private int benum;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", nullable = false, length = 23)
	private Date dateCreation;
	
	@Column(name = "NatDepense", nullable = false, length = 850)
	private String natDepense;
	
	@Column(name = "AuProfit")
	private String auProfit;
	
	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;
	
	@Column(name = "Dot_Initiale", precision = 18, scale = 0)
	private Long dotInitiale;
	
	@Column(name = "DispoAvant", precision = 18, scale = 0)
	private Long dispoAvant;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEtat", nullable = false, length = 23)
	private Date dateEtat;
	
	@Column(name = "IdUser", nullable = false, length = 5)
	private String idUser;
	
	@Column(name = "AvecDecision", nullable = false)
	private boolean avecDecision;
	
	@Column(name = "ApartirDemandLiq", nullable = false)
	private boolean apartirDemandLiq;
	
	@Column(name = "GRH", nullable = false)
	private boolean grh;
	
	@Column(name = "Receptionne", nullable = false)
	private boolean receptionne;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateValid", nullable = false, length = 23)
	private Date dateValid;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date_Creat", nullable = false, length = 23)
	private Date dateCreat;
	
	@Column(name = "CodLiq")
	private Long codLiq;
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "IdBord")
	//private BordTransmis bordTransmis;
	@Column(name = "IdBord")
	private Long idBord;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idContrat")
	private Contrats contrats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEng")
	private Engagements engagementsByIdEng;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Etat", nullable = false)
	private EtatDossier etatDossier;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtatTrans", nullable = false)
	private EtatTransmission etatTransmission;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Proced", nullable = false)
	private Procedures procedures;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false)
	private Budget budget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFourn", nullable = false)
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false)
	private Gestion gestion;
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "engagementsBordTransEng")
	private List<BordTransmis> bordTransmiss = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "engagementsByIdEng")
	private List<Engagements> engagementsForIdEng = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "engagements")
	private List<Liquidation> liquidations = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "engagements")
	private List<Decision> decisions = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "engagements")
	private List<PjengBrseZz> pjengBrseZzs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "engagements")
	private List<Mandats> mandats = new ArrayList<>();

	public Engagements(int benum, Date dateCreation, String natDepense, String auProfit, long montant, Long dotInitiale,
			Long dispoAvant, Date dateEtat, String idUser, boolean avecDecision, boolean apartirDemandLiq, boolean grh,
			boolean receptionne, Date dateValid, Date dateCreat, long codLiq,
			Contrats contrats, Engagements engagementsByIdEng, EtatDossier etatDossier,
			EtatTransmission etatTransmission, Procedures procedure, Budget budget, BudgetType budgetType,
			Destinataires destinataires, Gestion gestion, List<BordTransmis> bordTransmiss,
			List<Engagements> engagementsForIdEng, List<Liquidation> liquidations, List<Decision> decisions,
			List<PjengBrseZz> pjengBrseZzs, List<Mandats> mandats) {
		super();
		this.benum = benum;
		this.dateCreation = dateCreation;
		this.natDepense = natDepense;
		this.auProfit = auProfit;
		this.montant = montant;
		this.dotInitiale = dotInitiale;
		this.dispoAvant = dispoAvant;
		this.dateEtat = dateEtat;
		this.idUser = idUser;
		this.avecDecision = avecDecision;
		this.apartirDemandLiq = apartirDemandLiq;
		this.grh = grh;
		this.receptionne = receptionne;
		this.dateValid = dateValid;
		this.dateCreat = dateCreat;
		this.codLiq = codLiq;
		this.contrats = contrats;
		this.engagementsByIdEng = engagementsByIdEng;
		this.etatDossier = etatDossier;
		this.etatTransmission = etatTransmission;
		this.procedures = procedure;
		this.budget = budget;
		this.budgetType = budgetType;
		this.destinataires = destinataires;
		this.gestion = gestion;
		this.bordTransmiss = bordTransmiss;
		this.engagementsForIdEng = engagementsForIdEng;
		this.liquidations = liquidations;
		this.decisions = decisions;
		this.pjengBrseZzs = pjengBrseZzs;
		this.mandats = mandats;
	}

}
