package com.sigep.gbc.entity;
// Generated 27 juin 2022, 18:53:35 by Hibernate Tools 4.3.6.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entete generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "EnteteS")
public class Entete implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	private String codUser;
	
	private String niveau1;
	private String niveau2;
	private String niveau3;
	private String niveau4;
	private String abv1;
	private String abv2;
	private String abv3;
	private String abv4;
	private String complementNum;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "abrevEpe")
	private EnteteStructure enteteStructure;

}
