package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EtatTransmission generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "EtatTransmission", schema = "dbo")
public class EtatTransmission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "idEtatTrans", unique = true, nullable = false)
	private int idEtatTrans;
	
	@Column(name = "LibEtatTrans", nullable = false, length = 20)
	private String libEtatTrans;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatTransmission")
	private List<TitreDetail> titreDetails = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatTransmission")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatTransmission")
	private List<Engagements> engagements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatTransmissionByIdEtatTransM")
	private List<Mandats> mandatsByIdEtatTransM = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatTransmissionByIdEtatTransL")
	private List<Mandats> mandatsByIdEtatTransL = new ArrayList<>();
}
