package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EtatDossier generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "EtatDossier", schema = "dbo")
public class EtatDossier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "Etat", unique = true, nullable = false, length = 2)
	private String etat;
	
	@Column(name = "LibEtat", nullable = false, length = 50)
	private String libEtat;
	
	@Column(name = "AvecMotifR", nullable = false)
	private boolean avecMotifR;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatDossier")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatDossier")
	private List<Engagements> engagements = new ArrayList<>();

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatDossier")
	private List<TitreDetail> titreDetails = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatDossierByEtat")
	private List<Mandats> mandatsByEtat = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatDossierByEtatBl")
	private List<Mandats> mandatsByEtatBl = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatDossier")
	private List<CompteMouvement> compteMouvements = new ArrayList<>();
}
