package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EtatVersementElts generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "EtatVersementElts", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "EltRevers"))
public class EtatVersementElts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdEltR", unique = true, nullable = false)
	private Integer idEltR;
	
	@Column(name = "EltRevers", unique = true, nullable = false, length = 150)
	private String eltRevers;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPlan")
	private PlanComptable planComptable;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDest")
	private Destinataires destinataires;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatVersementElts")
	private List<CompteMouvEtatVelts> compteMouvEtatVelts = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatVersementElts")
	private List<CaisseSessionVente> caisseSessionVentes = new ArrayList<>();

	public EtatVersementElts(String eltRevers, PlanComptable planComptable, Destinataires destinataires,
			List<CompteMouvEtatVelts> compteMouvEtatVelts, List<CaisseSessionVente> caisseSessionVentes) {
		super();
		this.eltRevers = eltRevers;
		this.planComptable = planComptable;
		this.destinataires = destinataires;
		this.compteMouvEtatVelts = compteMouvEtatVelts;
		this.caisseSessionVentes = caisseSessionVentes;
	}
}
