package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FactureDetail generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "FactureDetail", schema = "dbo")
public class FactureDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdFactDetail", unique = true, nullable = false, length = 36)
	private String idFactDetail;
	
	@Column(name = "NumeroItem", nullable = false)
	private int numeroItem;
	
	@Column(name = "Designation", nullable = false, length = 850)
	private String designation;
	
	@Column(name = "Qtite", nullable = false, length = 18)
	private String qtite;
	
	@Column(name = "PrixUnitaire", nullable = false, precision = 18, scale = 0)
	private long prixUnitaire;
	
	@Column(name = "PrixTotal", nullable = false, precision = 18, scale = 0)
	private long prixTotal;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFact", nullable = false)
	private Factures factures;

	public FactureDetail(int numeroItem, String designation, String qtite, long prixUnitaire, long prixTotal,
			Factures factures) {
		super();
		this.numeroItem = numeroItem;
		this.designation = designation;
		this.qtite = qtite;
		this.prixUnitaire = prixUnitaire;
		this.prixTotal = prixTotal;
		this.factures = factures;
	}
}
