package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FactureType generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "FactureType", schema = "dbo")
public class FactureType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdTypFact", unique = true, nullable = false, length = 3)
	private String idTypFact;
	
	@Column(name = "LibelleTypFact", length = 50)
	private String libelleTypFact;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factureType")
	private List<Factures> factures = new ArrayList<>();
}
