package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.annotation.ReadOnlyProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Factures generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Factures", schema = "dbo")
public class Factures implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdFact", unique = true, nullable = false, precision = 18, scale = 0)
	private long idFact;
	
	@Column(name = "ObjetFact", nullable = false, length = 850)
	private String objetFact;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateFact", nullable = false, length = 23)
	private Date dateFact;
	
	@ReadOnlyProperty
	@Column(name = "NumeroFact")
	private String numeroFact;
	
	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;
	
	@Column(name = "Remise", nullable = false, precision = 18, scale = 0)
	private long remise;
	
	@Column(name = "TauxTVA", nullable = false, precision = 5)
	private BigDecimal tauxTva;
	
	@Column(name = "AvecTVA", nullable = false)
	private boolean avecTva;
	
	@ReadOnlyProperty
	@Column(name = "MontantHT", precision = 18, scale = 0)
	private Long montantHt;
	
	@ReadOnlyProperty
	@Column(name = "MontantTVA", precision = 18, scale = 0)
	private Long montantTva;
	
	@ReadOnlyProperty
	@Column(name = "MontantTTC", precision = 18, scale = 0)
	private Long montantTtc;
	
	@Column(name = "IdSignataire")
	private Integer idSignataire;
	
	@Column(name = "Signataire")
	private String signataire;
	
	@Column(name = "NomSign", length = 150)
	private String nomSign;
	
	@Column(name = "TitreHonoSign", length = 150)
	private String titreHonoSign;
	
	@Column(name = "NumChrono", nullable = false)
	private int numChrono;
	
	@Column(name = "ComplemaNum", nullable = false, length = 50)
	private String complemaNum;
	
	@Column(name = "IdFactParent", precision = 18, scale = 0)
	private Long idFactParent;
	
	@Column(name = "Valide", nullable = false)
	private boolean valide;
	
	@Column(name = "NumeroContate", length = 150)
	private String numeroContate;
	
	@Column(name = "Actif", nullable = false)
	private boolean actif;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdTypFact", nullable = false)
	private FactureType factureType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDebiteur", nullable = false)
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCpte", nullable = false)
	private Compte compte;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factures")
	private List<TitreEmis> titreEmis = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factures")
	private List<FactureDetail> factureDetails = new ArrayList<>();
}
