package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Fournisseurs generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Fournisseurs")
public class Fournisseurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "destinataires"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdFourn", unique = true, nullable = false, precision = 18, scale = 0)
	private long idFourn;
	
	@Column(name = "RaisonSociale")
	private String raisonSociale;
	
	@Column(name = "BP")
	private String bp;
	
	@Column(name = "Profession", length = 250)
	private String profession;
	
	@Column(name = "Telephone")
	private String telephone;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Destinataires destinataires;
}
