package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FraisInscriptionId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class FraisInscriptionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "IdFrais", nullable = false)
	private int idFrais;

	@Column(name = "TypeFrais", nullable = false)
	private int typeFrais;

	@Column(name = "Cycle", nullable = false, length = 2)
	private String cycle;

	@Column(name = "NumClasse", nullable = false)
	private int numClasse;
}
