package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FraisInscription generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "FraisInscription", schema = "Elev")
public class FraisInscription implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idFrais", column = @Column(name = "IdFrais", nullable = false)),
			@AttributeOverride(name = "typeFrais", column = @Column(name = "TypeFrais", nullable = false)),
			@AttributeOverride(name = "cycle", column = @Column(name = "Cycle", nullable = false, length = 2)),
			@AttributeOverride(name = "numClasse", column = @Column(name = "NumClasse", nullable = false)) })
	private FraisInscriptionId id;
	
	@Column(name = "FraisAnnuel", nullable = false, precision = 18, scale = 0)
	private long fraisAnnuel;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cycle", nullable = false, insertable = false, updatable = false)
	private Cycles cycles;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFrais", nullable = false, insertable = false, updatable = false)
	private FraisTextes fraisTextes;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TypeFrais", nullable = false, insertable = false, updatable = false)
	private TypesFrais typesFrais;
}
