package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * FraisTextes generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "FraisTextes", schema = "Elev")
public class FraisTextes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdFrais", unique = true, nullable = false)
	private int idFrais;

	@Column(name = "NumTexte", nullable = false, length = 550)
	private String numTexte;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateAppli", nullable = false, length = 23)
	private Date dateAppli;

	@Column(name = "Envigueur", nullable = false)
	private boolean envigueur;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fraisTextes")
	private List<FraisInscription> fraisInscriptions = new ArrayList<>();
}
