package com.sigep.gbc.entity;
// Generated 16 ao�t 2022, 19:00:48 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Gestion generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Gestion")
public class Gestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "Courante", unique = true, nullable = false)
	private short courante;
	
	@Column(name = "Libelle")
	private String libelle;
	
	@Column(name = "Etat")
	private String etat;
	
	@Column(name = "utilisation")
	private String utilisation;
	
	@OneToMany(mappedBy = "gestion", fetch = FetchType.LAZY)
	private List<AccesLigneBudgetaire>  accesLigneBudgetaires = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<BudgetTypeGestion> budgetTypeGestions = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<Budget> budgets = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stElements")
	private List<StElementsNomencla> stElementsNomenclas = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<Engagements> engagements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<Mandats> mandats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<CompteMouvement> compteMouvements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<ReportBudgetaire> reportBudgetaires = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<ReportCompte> reportComptes = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gestion")
	private List<RetenuTitreRecouv> retenuTitreRecouvs = new ArrayList<>();
	
	public void addAccesLigneBudgetaire(AccesLigneBudgetaire accesLigneBudgetaire) {
		accesLigneBudgetaires.add(accesLigneBudgetaire);
	}
	
	public void removeAccesLigneBudgetaire(AccesLigneBudgetaire accesLigneBudgetaire) {
		accesLigneBudgetaires.remove(accesLigneBudgetaire);
	}
}
