package com.sigep.gbc.entity;
// Generated 28 juin 2022, 18:45:14 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * GrpeCode generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "GrpeCode")
public class GrpeCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "grpe", unique = true, nullable = false)
	private String grpe;
	
	@Column(name = "LibelleGrpe")
	private String libelleGrpe;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grpeCode")
	private List<AccesCode> accesCodes = new ArrayList<>();
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "grpeCodes")
	private List<AccesCodeNiveau> accesCodeNiveaus = new ArrayList<>();
	
	public void addAcccesCode(AccesCode accesCode) {
		accesCodes.add(accesCode);
	}
	
	public void removeAccesCode(AccesCode accesCode) {
		accesCodes.remove(accesCode);
	}
	
	public void addAcccesCodeNiveau(AccesCodeNiveau accesCodeNiveau) {
		accesCodeNiveaus.add(accesCodeNiveau);
	}
	
	public void removeAccesCodeNiveau(AccesCodeNiveau accesCodeNiveau) {
		accesCodeNiveaus.remove(accesCodeNiveau);
	}

}
