package com.sigep.gbc.entity;
// Generated 7 févr. 2024, 00:42:44 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * HistoActionS generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "HistoActionS", schema = "dbo")
public class HistoActionS implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dateAct", column = @Column(name = "DateAct", nullable = false, length = 23)),
			@AttributeOverride(name = "codH", column = @Column(name = "CodH", nullable = false, length = 36)) })
	private HistoActionSId id;
	
	@Column(name = "Action")
	private String action;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodH", nullable = false, insertable = false, updatable = false)
	private HistoConS histoConS;
}
