package com.sigep.gbc.entity;
// Generated 7 févr. 2024, 00:42:44 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * HistoActionSId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class HistoActionSId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "DateAct", nullable = false, length = 23)
	private Date dateAct;

	@Column(name = "CodH", nullable = false, length = 36)
	private String codH;
}
