package com.sigep.gbc.entity;
// Generated 7 févr. 2024, 00:42:44 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * HistoConS generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "HistoConS", schema = "dbo")
public class HistoConS implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CodH", unique = true, nullable = false, length = 36)
	private String codH;
	
	@Column(name = "IDL", nullable = false, length = 5)
	private String idl;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateConnexion", nullable = false, length = 23)
	private Date dateConnexion;

	@Column(name = "PC", length = 250)
	private String pc;

	@Column(name = "AdressMac", length = 50)
	private String adressMac;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "histoConS")
	private List<HistoActionS> histoActionSs = new ArrayList<>();

	public HistoConS(String idl, Date dateConnexion, String pc, String adressMac, List<HistoActionS> histoActionSs) {
		super();
		this.idl = idl;
		this.dateConnexion = dateConnexion;
		this.pc = pc;
		this.adressMac = adressMac;
		this.histoActionSs = histoActionSs;
	}
}
