package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Imputation generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Imputation", schema = "dbo")
public class Imputation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Num", unique = true, nullable = false, length = 36)
	private String num;
	
	@Column(name = "Gestion")
	private Integer gestion;

	@Column(name = "CS")
	private String cs;

	@Column(name = "Titre")
	private String titre;

	@Column(name = "Section")
	private String section;

	@Column(name = "Chap")
	private String chap;

	@Column(name = "Article")
	private String article;

	@Column(name = "Parag")
	private String parag;

	@Column(name = "Rubr")
	private String rubr;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id", nullable = false)
	private Penalite penalite;

	public Imputation(Integer gestion, String cs, String titre, String section, String chap, String article,
			String parag, String rubr, Penalite penalite) {
		super();
		this.gestion = gestion;
		this.cs = cs;
		this.titre = titre;
		this.section = section;
		this.chap = chap;
		this.article = article;
		this.parag = parag;
		this.rubr = rubr;
		this.penalite = penalite;
	}
}
