package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * InfoInscriptionEleve generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "InfoInscriptionEleve", schema = "Elev")
public class InfoInscriptionEleve implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "debiteurEleve"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdDebiteur", unique = true, nullable = false, precision = 18, scale = 0)
	private long idDebiteur;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateInscription", nullable = false, length = 10)
	private Date dateInscription;

	@Temporal(TemporalType.DATE)
	@Column(name = "DateSortie", length = 10)
	private Date dateSortie;

	@Column(name = "Actif")
	private Boolean actif;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AnneInscription", nullable = false)
	private AnneeScolaire anneeScolaire;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private DebiteurEleve debiteurEleve;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPays", nullable = false)
	private Pays pays;

	public InfoInscriptionEleve(Date dateInscription, Date dateSortie, Boolean actif, AnneeScolaire anneeScolaire,
			DebiteurEleve debiteurEleve, Pays pays) {
		super();
		this.dateInscription = dateInscription;
		this.dateSortie = dateSortie;
		this.actif = actif;
		this.anneeScolaire = anneeScolaire;
		this.debiteurEleve = debiteurEleve;
		this.pays = pays;
	}
}
