package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * InscritPour generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "InscritPour", schema = "Elev", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IdDebiteur", "AnneD" }))
public class InscritPour implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idInscritPour", unique = true, nullable = false, length = 36)
	private String idInscritPour;
	
	@Column(name = "IdFrais", nullable = false)
	private int idFrais;

	@Column(name = "TypeFrais", nullable = false)
	private int typeFrais;

	@Column(name = "IdSection", nullable = false, length = 10)
	private String idSection;

	@Column(name = "NumClasse", nullable = false)
	private int numClasse;

	@Column(name = "Frais", nullable = false, precision = 18, scale = 0)
	private long frais;

	@Column(name = "Ajuste", nullable = false, precision = 18, scale = 0)
	private long ajuste;

	@Column(name = "FraisApayer", scale = 0)
	private BigInteger fraisApayer;

	@Column(name = "Acompte", nullable = false, precision = 18, scale = 0)
	private long acompte;

	@Column(name = "IdDestResp", precision = 18, scale = 0)
	private Long idDestResp;

	@Column(name = "IdDest", nullable = false, precision = 18, scale = 0)
	private long idDest;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AnneD", nullable = false)
	private AnneeScolaire anneeScolaire;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDebiteur", nullable = false)
	private DebiteurEleve debiteurEleve;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inscritPour")
	private List<AcompteFrais> acompteFrais = new ArrayList<>();

	public InscritPour(int idFrais, int typeFrais, String idSection, int numClasse, long frais, long ajuste,
			BigInteger fraisApayer, long acompte, Long idDestResp, long idDest, AnneeScolaire anneeScolaire,
			DebiteurEleve debiteurEleve, List<AcompteFrais> acompteFrais) {
		super();
		this.idFrais = idFrais;
		this.typeFrais = typeFrais;
		this.idSection = idSection;
		this.numClasse = numClasse;
		this.frais = frais;
		this.ajuste = ajuste;
		this.fraisApayer = fraisApayer;
		this.acompte = acompte;
		this.idDestResp = idDestResp;
		this.idDest = idDest;
		this.anneeScolaire = anneeScolaire;
		this.debiteurEleve = debiteurEleve;
		this.acompteFrais = acompteFrais;
	}
}
