package com.sigep.gbc.entity;
// Generated 15 nov. 2022, 12:01:26 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * InstitutFinAgence generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "InstitutFinAgence")
public class InstitutFinAgence implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdAgence", unique = true, nullable = false, length = 36)
	private String idAgence;
	
	@Column(name = "CodeAgence", nullable = false)
	private String codeAgence;
	
	@Column(name = "LibelleAgence", nullable = false, length = 50)
	private String libelleAgence;
	
	@Column(name = "DomicilieA", nullable = false, length = 150)
	private String domicilieA;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Abreviation", nullable = false)
	private InstitutFinancier institutFinancier;

	public InstitutFinAgence(String codeAgence, String libelleAgence, String domicilieA,
			InstitutFinancier institutFinancier) {
		super();
		this.codeAgence = codeAgence;
		this.libelleAgence = libelleAgence;
		this.domicilieA = domicilieA;
		this.institutFinancier = institutFinancier;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institutFinAgence")
	private List<CompteDestinataire> compteDestinataires = new ArrayList<>();
}
