package com.sigep.gbc.entity;
// Generated 15 nov. 2022, 12:01:26 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * InstitutFinancier generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "InstitutFinancier", uniqueConstraints = @UniqueConstraint(columnNames = "IdDest"))
public class InstitutFinancier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "Abreviation", unique = true, nullable = false, length = 20)
	private String abreviation;
	
	@Column(name = "Libelle", nullable = false, length = 550)
	private String libelle;
	
	@Column(name = "AddresseA", length = 550)
	private String addresseA;
	
	@Column(name = "TransiArct", length = 10)
	private String transiArct;
	
	@Column(name = "CodeBanque", nullable = false, length = 5)
	private String codeBanque;
	
	@Column(name = "LibCourtMinus", length = 150)
	private String libCourtMinus;
	
	@Column(name = "LibCourtMajus", length = 150)
	private String libCourtMajus;
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDest", nullable = false, unique = true)
	private Destinataires destinataires;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institutFinancier")
	private List<InstitutFinAgence> institutFinAgences = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institutFinancier")
	private List<CompteDestinataire> compteDestinataires = new ArrayList<>();
}
