package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JournalAction generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "JournalAction", schema = "dbo")
public class JournalAction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "Journa", unique = true, nullable = false, length = 6)
	private String journa;
	
	@Column(name = "LibelleJourna", nullable = false, length = 50)
	private String libelleJourna;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journalAction")
	private List<JournalPiece> journalPieces = new ArrayList<>();
}
