package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JournalOperation generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "JournalOperation", schema = "dbo")
public class JournalOperation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "Operat", unique = true, nullable = false, length = 1)
	private String operat;
	
	@Column(name = "LibelleOperat", nullable = false, length = 50)
	private String libelleOperat;
	
	@Column(name = "LibelleJrnl", length = 50)
	private String libelleJrnl;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journalOperation")
	private List<JournalPiece> journalPieces = new ArrayList<>();
}
