package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JournalPiece generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "JournalPiece", schema = "dbo")
public class JournalPiece implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdPieceJournal", unique = true, nullable = false, precision = 38, scale = 0)
	private BigInteger idPieceJournal;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBord")
	private CompteMouvement compteMouvement;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Journa", nullable = false)
	private JournalAction journalAction;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Operat", nullable = false)
	private JournalOperation journalOperation;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdChqVir")
	private MandatLettragPaie mandatLettragPaie;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand")
	private Mandats mandatsByNumMand;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMandRetenu")
	private Mandats mandatsByIdMandRetenu;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodRecouv")
	private Recouvrements recouvrements;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdReport")
	private ReportAnouveau reportAnouveau;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDRTR")
	private RetenuTitreRecouv retenuTitreRecouv;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodTitr")
	private TitreEmis titreEmis;
}
