package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JustificatifPj generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "JustificatifPJ", schema = "dbo")
public class JustificatifPj implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	private String id;
	
	@Column(name = "Piece", nullable = false, length = 250)
	private String piece;
	
	@Column(name = "Numero", length = 50)
	private String numero;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DatePJ", length = 10)
	private Date datePj;
	
	@Column(name = "MontantPJ", nullable = false, precision = 18, scale = 0)
	private long montantPj;
	
	@Column(name = "FournisseurBenef", length = 300)
	private String fournisseurBenef;
	
	@Column(name = "NumOrdre", nullable = false)
	private int numOrdre;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdJustif", nullable = false)
	private Justificatif justificatif;

	public JustificatifPj(String piece, String numero, Date datePj, long montantPj, String fournisseurBenef,
			int numOrdre, Justificatif justificatif) {
		super();
		this.piece = piece;
		this.numero = numero;
		this.datePj = datePj;
		this.montantPj = montantPj;
		this.fournisseurBenef = fournisseurBenef;
		this.numOrdre = numOrdre;
		this.justificatif = justificatif;
	}
}
