package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Justificatif generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Justificatif", schema = "dbo")
public class Justificatif implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdJustif", unique = true, nullable = false, length = 36)
	private String idJustif;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateJustif", nullable = false, length = 10)
	private Date dateJustif;

	@Column(name = "NatureActeJustif", nullable = false, length = 50)
	private String natureActeJustif;

	@Column(name = "NumActeJustif", length = 50)
	private String numActeJustif;

	@Temporal(TemporalType.DATE)
	@Column(name = "DateActeJustif", length = 10)
	private Date dateActeJustif;

	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;

	@Column(name = "UserNameUpdate", nullable = false, length = 5)
	private String userNameUpdate;

	@Column(name = "Valide", nullable = false)
	private boolean valide;

	@Column(name = "UserNameValid", length = 5)
	private String userNameValid;

	@Column(name = "IdBudget", nullable = false)
	private int idBudget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand", nullable = false)
	private Mandats mandats;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "justificatif")
	private List<JustificatifPj> justificatifPjs = new ArrayList<>();

	public Justificatif(Date dateJustif, String natureActeJustif, String numActeJustif, Date dateActeJustif,
			long montant, String userNameUpdate, boolean valide, String userNameValid, int idBudget, Mandats mandats,
			List<JustificatifPj> justificatifPjs) {
		super();
		this.dateJustif = dateJustif;
		this.natureActeJustif = natureActeJustif;
		this.numActeJustif = numActeJustif;
		this.dateActeJustif = dateActeJustif;
		this.montant = montant;
		this.userNameUpdate = userNameUpdate;
		this.valide = valide;
		this.userNameValid = userNameValid;
		this.idBudget = idBudget;
		this.mandats = mandats;
		this.justificatifPjs = justificatifPjs;
	}
}
