package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.annotation.ReadOnlyProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Liquidation generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Liquidation", schema = "dbo")
public class Liquidation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "CodLiq", unique = true, nullable = false, precision = 18, scale = 0)
	private long codLiq;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;
	
	@Column(name = "NumBL", nullable = false)
	private int numBl;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateLiq", nullable = false, length = 23)
	private Date dateLiq;
	
	@Column(name = "Objet", nullable = false)
	private String objet;
	
	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;

	@Column(name = "MontEngage", nullable = false, precision = 18, scale = 0)
	private long montEngage;
	
	@Column(name = "MontDjaLiq", nullable = false, precision = 18, scale = 0)
	private long montDjaLiq;
	
	@Column(name = "Modifiable", nullable = false)
	private boolean modifiable;
	
	@Column(name = "IdUser", nullable = false, length = 7)
	private String idUser;
	
	@ReadOnlyProperty
	@Column(name = "NumeroDemande", insertable = false, updatable = false)
	private String numeroDemande;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateModif", nullable = false, length = 23)
	private Date dateModif;
	
	@Column(name = "Actif", nullable = false)
	private boolean actif;
	
	@Column(name = "IdBudget", nullable = false)
	private int idBudget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CompteFourn")
	private CompteDestinataire compteDestinataire;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idContrat")
	private Contrats contrats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumBE")
	private Engagements engagements;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFourn", nullable = false)
	private Destinataires destinataires;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "liquidation")
	//private List<Mandats> mandats = new ArrayList<>();
}
