package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Livraisons generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Livraisons", schema = "dbo")
public class Livraisons implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "NumD", unique = true, nullable = false, length = 36)
	private String numD;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 23)
	private Date date;

	@Column(name = "Montant", scale = 4)
	private BigDecimal montant;

	@Column(name = "TypeMont")
	private String typeMont;

	@Column(name = "NbJrs")
	private Integer nbJrs;

	@Column(name = "MontantPena", precision = 18, scale = 0)
	private Long montantPena;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdContrat")
	private Contrats contrats;

	public Livraisons(Date date, BigDecimal montant, String typeMont, Integer nbJrs, Long montantPena,
			Contrats contrats) {
		super();
		this.date = date;
		this.montant = montant;
		this.typeMont = typeMont;
		this.nbJrs = nbJrs;
		this.montantPena = montantPena;
		this.contrats = contrats;
	}
}
