package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MandatsCloture generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "MandatsCloture", schema = "dbo")
public class MandatsCloture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "mandats"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "NumMand", unique = true, nullable = false, precision = 18, scale = 0)
	private long numMand;
	
	@Column(name = "Observations", length = 1050)
	private String observations;

	@Column(name = "Apurer", nullable = false)
	private boolean apurer;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Mandats mandats;

	public MandatsCloture(String observations, boolean apurer, Mandats mandats) {
		super();
		this.observations = observations;
		this.apurer = apurer;
		this.mandats = mandats;
	}
}
