package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Mandats generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Mandats", schema = "dbo")
public class Mandats implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "NumMand", unique = true, nullable = false, precision = 18, scale = 0)
	private long numMand;
	
	@Column(name = "MandNum", nullable = false)
	private int mandNum;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateMand", nullable = false, length = 23)
	private Date dateMand;
	
	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEtat", nullable = false, length = 23)
	private Date dateEtat;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePaie", length = 23)
	private Date datePaie;
	
	@Column(name = "MontantPaie", precision = 18, scale = 0)
	private Long montantPaie;
	
	@Column(name = "IdCompte")
	private String idCompte;
	
	@Column(name = "IdUser", nullable = false, length = 5)
	private String idUser;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePosition", length = 23)
	private Date datePosition;

	@Column(name = "BENum", nullable = false)
	private int benum;

	@Column(name = "NumBL", nullable = false)
	private int numBl;
	
	@Column(name = "Objet", nullable = false)
	private String objet;

	@Column(name = "MontEngage", nullable = false, precision = 18, scale = 0)
	private long montEngage;

	@Column(name = "MontDjaLiq", nullable = false, precision = 18, scale = 0)
	private long montDjaLiq;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEtatBL", nullable = false, length = 23)
	private Date dateEtatBl;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePEC", length = 23)
	private Date datePec;
	
	@Column(name = "Receptionne", nullable = false)
	private boolean receptionne;
	
	@Column(name = "GenererOV", nullable = false)
	private boolean genererOv;

	@Column(name = "AvecReversement", nullable = false)
	private boolean avecReversement;

	@Column(name = "Precompte", nullable = false, precision = 18, scale = 0)
	private long precompte;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePrecompte", length = 23)
	private Date datePrecompte;

	@Column(name = "UserPrecompte", length = 5)
	private String userPrecompte;

	@Column(name = "DateValid", nullable = false, length = 23)
	private Date dateValid;

	@Column(name = "IdFiche", nullable = false, precision = 18, scale = 0)
	private long idFiche;
	
	@Column(name = "MontantTotalPEC", nullable = false, precision = 18, scale = 0)
	private long montantTotalPec;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date_Creat", nullable = false, length = 23)
	private Date dateCreat;

	@Column(name = "EstOrdre", nullable = false)
	private boolean estOrdre;

	@Column(name = "MandNumApresVisaCf", nullable = false)
	private int mandNumApresVisaCf;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtatTransL", nullable = false)
	private EtatTransmission etatTransmissionByIdEtatTransL;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtatTransM", nullable = false)
	private EtatTransmission etatTransmissionByIdEtatTransM;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBordEmis")
	private BordereauEmismandats bordereauEmismandats;
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "IDbord")
	//private BordTransmis bordTransmis;
	@Column(name = "IdBord")
	private Long idBord;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false)
	private Budget budget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CompteFourn")
	private CompteDestinataire compteDestinataire;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idContrat")
	private Contrats contrats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFourn", nullable = false)
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false)
	private Gestion gestion;
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "CodLiq")
	//private Liquidation liquidation; // A Definir service
	@Column(name = "CodLiq")
	private Long codLiq;
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "IdLettrage")
	//private MandatLettrages mandatLettrages; // A Definir service
	@Column(name = "IdLettrage")
	private String idLettrage;
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "ModePaie")
	//private ModePaiement modePaiement; // A Definir service
	@Column(name = "ModePaie")
	private String idModePaie;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumBE", nullable = false)
	private Engagements engagements;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Etat", nullable = false)
	private EtatDossier etatDossierByEtat;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EtatBL", nullable = false)
	private EtatDossier etatDossierByEtatBl;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMandParent")
	private Mandats mandats;
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "mandatsBordTransMand")
	private List<BordTransmis> bordTransmisBordTransMand = new ArrayList<>();
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "mandatsBordTransLiq")
	private List<BordTransmis> bordTransmisBordTransLiq = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<RetenusQuitOrdre> retenusQuitOrdres = new ArrayList<>();
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "mandats")
	private MandatsCloture mandatsCloture;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<PieceJustifComplement> pieceJustifComplements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<CompteMouvementMandR> compteMouvementMandRs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<RetenuTitreRecouv> retenuTitreRecouvs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<MandatLettragPaie> mandatLettragPaies = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<ChequesVirements> chequesVirements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<Mandats> mandatss = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandatsByNumMand")
	private List<JournalPiece> journalPiecesForNumMand = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandatsByIdMandRetenu")
	private List<JournalPiece> journalPiecesForIdMandRetenu = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<Justificatif> justificatifs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<MandatPec> mandatPecs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<BordMand> bordMands = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandats")
	private List<Retenus> retenus = new ArrayList<>();
}
