package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MandatLettragPaie generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "MandatLettragPaie", schema = "dbo")
public class MandatLettragPaie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idChqVir", unique = true, nullable = false, length = 36)
	private String idChqVir;
	
	
	@Column(name = "ModePaie", nullable = false, length = 3)
	private String modePaie;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DatePosiChqVir", nullable = false, length = 10)
	private Date datePosiChqVir;
	
	@Column(name = "Libelle", length = 850)
	private String libelle;
	
	@Column(name = "AuProfitDe", length = 300)
	private String auProfitDe;
	
	@Column(name = "IdBudget", nullable = false)
	private int idBudget;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;
	
	@Column(name = "Piece", nullable = false)
	private String piece;
	
	@Column(name = "Paie", nullable = false)
	private int paie;
	

	@Column(name = "GenererOV", nullable = false)
	private boolean genererOv;
	
	@Column(name = "MontantNetPaye", nullable = false, precision = 18, scale = 0)
	private long montantNetPaye;
	
	@Column(name = "MontantBrut", nullable = false, precision = 18, scale = 0)
	private long montantBrut;
	
	@Column(name = "CompteFourn", length = 36)
	private String compteFourn;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdLettrage")
	private MandatLettrages mandatLettrages;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand")
	private Mandats mandats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDest")
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCompteC", nullable = false)
	private Compte compte;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandatLettragPaie")
	private List<MandatsModePaie> mandatsModePaies = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandatLettragPaie")
	private List<PaiementCpte> paiementCptes = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandatLettragPaie")
	private List<JournalPiece> journalPieces = new ArrayList<>();
}
