package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MandatsModePaie generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Mandats_ModePaie", schema = "dbo")
public class MandatsModePaie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false, length = 36)
	private String id;
	
	@Column(name = "ModePaie", nullable = false, length = 3)
	private String modePaie;

	@Column(name = "NumModePaie", length = 150)
	private String numModePaie;

	@Temporal(TemporalType.DATE)
	@Column(name = "DateModePaie", length = 10)
	private Date dateModePaie;

	@Column(name = "MontantChqVir", nullable = false, precision = 18, scale = 0)
	private long montantChqVir;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idChqVir", nullable = false)
	private MandatLettragPaie mandatLettragPaie;

	public MandatsModePaie(String modePaie, String numModePaie, Date dateModePaie, long montantChqVir,
			MandatLettragPaie mandatLettragPaie) {
		super();
		this.modePaie = modePaie;
		this.numModePaie = numModePaie;
		this.dateModePaie = dateModePaie;
		this.montantChqVir = montantChqVir;
		this.mandatLettragPaie = mandatLettragPaie;
	}
}
