package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MandatPec generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "MandatPEC", schema = "dbo")
public class MandatPec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numMand", column = @Column(name = "NumMand", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "idComptePec", column = @Column(name = "IdComptePec", nullable = false)) })
	private MandatPecId id;
	
	@Column(name = "MontantPEC", nullable = false, precision = 18, scale = 0)
	private long montantPec;
	
	@Column(name = "PourPrecompte", nullable = false)
	private boolean pourPrecompte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand", nullable = false, insertable = false, updatable = false)
	private Mandats mandats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdComptePec", nullable = false, insertable = false, updatable = false)
	private Compte compte;
}
