package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MandatLettrages generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "MandatLettrages", schema = "dbo")
public class MandatLettrages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdLettrage", unique = true, nullable = false, length = 36)
	private String idLettrage;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateLettrage", nullable = false, length = 23)
	private Date dateLettrage;
	
	@Column(name = "MontantPEC", nullable = false, precision = 18, scale = 0)
	private long montantPec;
	
	@Column(name = "MontantPaie", nullable = false, precision = 18, scale = 0)
	private long montantPaie;
	
	@Column(name = "IdBudget", nullable = false)
	private int idBudget;
	

	@Column(name = "Chap", nullable = false)
	private String chap;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserName", nullable = false)
	private AccesCode accesCode;
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "mandatLettrages")
	private ModePaieMand modePaieMand;
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandatLettrages")
	//private List<Mandats> mandats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mandatLettrages")
	private List<MandatLettragPaie> mandatLettragPaies = new ArrayList<>();

	public MandatLettrages(Date dateLettrage, long montantPec, long montantPaie, int idBudget, String chap,
			AccesCode accesCode, ModePaieMand modePaieMand,
			List<MandatLettragPaie> mandatLettragPaies) {
		super();
		this.dateLettrage = dateLettrage;
		this.montantPec = montantPec;
		this.montantPaie = montantPaie;
		this.idBudget = idBudget;
		this.chap = chap;
		this.accesCode = accesCode;
		this.modePaieMand = modePaieMand;
		this.mandatLettragPaies = mandatLettragPaies;
	}
}
