package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ModePaiement generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ModePaiement", schema = "dbo")
public class ModePaiement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdModePaie", unique = true, nullable = false, length = 3)
	private String idModePaie;
	
	@Column(name = "LibModePaie", nullable = false, length = 25)
	private String libModePaie;
	
	@Column(name = "NomDoc", nullable = false, length = 5)
	private String nomDoc;
	
	@Column(name = "avecNum", nullable = false)
	private boolean avecNum;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modePaiement")
	private List<CompteMouvement> compteMouvements = new ArrayList<>();
	
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "modePaiement")
	//private List<Mandats> mandats = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modePaiement")
	private List<Recouvrements> recouvrements = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modePaiement")
	private List<RetenuTitreRecouv> retenuTitreRecouvs = new ArrayList<>();
}
