package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ModePaieMand generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "ModePaieMand", schema = "dbo")
public class ModePaieMand implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "mandatLettrages"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdLettrage", unique = true, nullable = false, length = 36)
	private String idLettrage;
	
	@Column(name = "ModePaie", length = 150)
	private String modePaie;
	
	@Column(name = "NumModePaie", length = 1776)
	private String numModePaie;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private MandatLettrages mandatLettrages;

	public ModePaieMand(String modePaie, String numModePaie, MandatLettrages mandatLettrages) {
		super();
		this.modePaie = modePaie;
		this.numModePaie = numModePaie;
		this.mandatLettrages = mandatLettrages;
	}
}
