package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MotifsRejetDossier generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "MotifsRejetDossier", schema = "dbo")
public class MotifsRejetDossier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Id_motif", unique = true, nullable = false, length = 36)
	private String idMotif;
	
	@Column(name = "Motifs", nullable = false)
	private String motifs;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSaisie", nullable = false, length = 23)
	private Date dateSaisie;
	
	@Column(name = "NumBE", precision = 18, scale = 0)
	private Long numBe;
	
	@Column(name = "NumMand", precision = 18, scale = 0)
	private Long numMand;
	
	@Column(name = "CodLiq", precision = 18, scale = 0)
	private Long codLiq;
	
	@Column(name = "IdTitre", precision = 18, scale = 0)
	private Long idTitre;
	
	@Column(name = "UserName", nullable = false, length = 5)
	private String userName;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEnreg", nullable = false, length = 23)
	private Date dateEnreg;
	
	@Column(name = "Actif", nullable = false)
	private boolean actif;
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "motifsRejetDossiers")
	private List<BordTransmis> bordTransmis = new ArrayList<>();
}
