package com.sigep.gbc.entity;
// Generated 24 ao�t 2022, 13:59:44 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * NiveauPlanComptable generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "NiveauPlanComptable")
public class NiveauPlanComptable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "Niveau", unique = true, nullable = false)
	private int niveau;
	
	@Column(name = "IntituleNiveau")
	private String intituleNiveau;
	
	@Column(name = "Description")
	private String description;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "niveauPlanComptable")
	private List<PlanComptable> planComptables = new ArrayList<>();
}
