package com.sigep.gbc.entity;
// Generated 16 ao�t 2022, 19:00:48 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * NomenclatureD generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "NomenclatureD")
public class NomenclatureD implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "NumNo", unique = true, nullable = false)
	private String numNo;
	
	@Column(name = "Titre")
	private String titre;
	
	@Column(name = "Section")
	private String section;
	
	@Column(name = "Chap")
	private String chap;
	
	@Column(name = "Art")
	private String art;
	
	@Column(name = "Parag")
	private String parag;
	
	@Column(name = "Rub")
	private String rub;
	
	@Column(name = "Intitule", length = 450)
	private String intitule;
	
	@Column(name = "IdPlan")
	private String idPlan;
	
	@Column(name = "Dot_Est_Exec", nullable = false)
	private Boolean dotEstExec;
	
	@Column(name = "CodHierarchiq")
	private String codHierarchiq;
}
