package com.sigep.gbc.entity;
// Generated 27 juin 2022, 18:53:35 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * NumerotationMandat generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "NumerotationMandatS")
public class NumerotationMandat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	private int mandNumApresVisaCf;
	
	@Column(name = "descriptions", nullable = false)
	private String descriptions;
	
	@OneToMany(mappedBy = "numerotationMandat", fetch = FetchType.LAZY)
	private List<EnteteStructure> enteteStructures = new ArrayList<>();

	public NumerotationMandat(String descriptions, List<EnteteStructure> enteteStructures) {
		super();
		this.descriptions = descriptions;
		this.enteteStructures = enteteStructures;
	}
	
	public void addEnteteStructure(EnteteStructure enteteStructure) {
		enteteStructures.add(enteteStructure);
	}
	
	public void removeEnteteStructure(EnteteStructure enteteStructure) {
		enteteStructures.remove(enteteStructure);
	}
}
