package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PaiementCpte generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PaiementCpte", schema = "dbo")
public class PaiementCpte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idChqVir", column = @Column(name = "idChqVir", nullable = false, length = 36)),
			@AttributeOverride(name = "idCompte", column = @Column(name = "IdCompte", nullable = false)) })
	private PaiementCpteId id;
	
	@Column(name = "Debiter", nullable = false, precision = 18, scale = 0)
	private long debiter;
	
	@Column(name = "Crediter", nullable = false, precision = 18, scale = 0)
	private long crediter;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idChqVir", nullable = false, insertable = false, updatable = false)
	private MandatLettragPaie mandatLettragPaie;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCompte", nullable = false, insertable = false, updatable = false)
	private Compte compte;
}
