package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Pays generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Pays", schema = "Elev")
public class Pays implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdPays", unique = true, nullable = false)
	private int idPays;
	
	@Column(name = "NomPays", nullable = false)
	private String nomPays;
	
	@Column(name = "NationaliteM", nullable = false, length = 50)
	private String nationaliteM;
	
	@Column(name = "NationaliteF", nullable = false, length = 50)
	private String nationaliteF;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TypeFrais", nullable = false)
	private TypesFrais typesFrais;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	private List<InfoInscriptionEleve> infoInscriptionEleves = new ArrayList<>();
}
