package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Penalite generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Penalite", schema = "dbo")
public class Penalite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Id", unique = true, nullable = false, length = 36)
	private String id;
	
	@Column(name = "Annee")
	private Integer annee;

	@Column(name = "Numero", nullable = false)
	private int numero;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSaisi", length = 23)
	private Date dateSaisi;

	@Column(name = "Cas")
	private String cas;

	@Column(name = "Imputation")
	private String imputation;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateNormale", length = 23)
	private Date dateNormale;

	@Column(name = "NbreJours")
	private String nbreJours;

	@Column(name = "Suspension")
	private String suspension;

	@Column(name = "MontantPenal", precision = 18, scale = 0)
	private Long montantPenal;

	@Column(name = "DetailDelai")
	private String detailDelai;

	@Column(name = "DetailDatN")
	private String detailDatN;

	@Column(name = "DetailDatEf")
	private String detailDatEf;

	@Column(name = "DetailDemar")
	private String detailDemar;

	@Column(name = "Pec")
	private Boolean pec;

	@Column(name = "NumMand", precision = 18, scale = 0)
	private Long numMand;
	
	@Column(name = "IdLogin", length = 5)
	private String idLogin;
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdContrat")
	private Contrats contrats;
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "AmpliaPenal", schema = "dbo", joinColumns = {@JoinColumn(name = "Id", nullable = false, updatable = false) }, 
			inverseJoinColumns = {@JoinColumn(name = "Amp", nullable = false, updatable = false) }
	)
	private List<Ampliataires> ampliataires = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "penalite")
	private List<Imputation> imputations = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "penalite")
	private List<Retenus> retenus = new ArrayList<>();

	public Penalite(Integer annee, int numero, Date dateSaisi, String cas, String imputation, Date dateNormale,
			String nbreJours, String suspension, Long montantPenal, String detailDelai, String detailDatN,
			String detailDatEf, String detailDemar, Boolean pec, Long numMand, String idLogin, Contrats contrats,
			List<Ampliataires> ampliataires, List<Imputation> imputations, List<Retenus> retenus) {
		super();
		this.annee = annee;
		this.numero = numero;
		this.dateSaisi = dateSaisi;
		this.cas = cas;
		this.imputation = imputation;
		this.dateNormale = dateNormale;
		this.nbreJours = nbreJours;
		this.suspension = suspension;
		this.montantPenal = montantPenal;
		this.detailDelai = detailDelai;
		this.detailDatN = detailDatN;
		this.detailDatEf = detailDatEf;
		this.detailDemar = detailDemar;
		this.pec = pec;
		this.numMand = numMand;
		this.idLogin = idLogin;
		this.contrats = contrats;
		this.ampliataires = ampliataires;
		this.imputations = imputations;
		this.retenus = retenus;
	}
}
