package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PieceJustif generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "PieceJustif", schema = "dbo")
public class PieceJustif implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CodPj", unique = true, nullable = false, length = 36)
	private String codPj;
	
	@Column(name = "NumBE", precision = 18, scale = 0)
	private Long numBe;

	@Column(name = "CodLiq", precision = 18, scale = 0)
	private Long codLiq;

	@Column(name = "NumMand", precision = 18, scale = 0)
	private Long numMand;

	@Column(name = "PieceJustificative")
	private String pieceJustificative;

	@Column(name = "Numero")
	private String numero;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePj", length = 23)
	private Date datePj;

	@Column(name = "Montant", precision = 18, scale = 0)
	private Long montant;

	@Column(name = "idRetenu", length = 36)
	private String idRetenu;

	@Column(name = "IdBord", precision = 18, scale = 0)
	private Long idBord;

	public PieceJustif(Long numBe, Long codLiq, Long numMand, String pieceJustificative, String numero, Date datePj,
			Long montant, String idRetenu, Long idBord) {
		super();
		this.numBe = numBe;
		this.codLiq = codLiq;
		this.numMand = numMand;
		this.pieceJustificative = pieceJustificative;
		this.numero = numero;
		this.datePj = datePj;
		this.montant = montant;
		this.idRetenu = idRetenu;
		this.idBord = idBord;
	}
}
