package com.sigep.gbc.entity;
// Generated 4 oct. 2022, 13:21:13 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Pj generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "PJ")
public class Pj implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CodPJ", unique = true, nullable = false)
	private Integer codPj;
	
	@Column(name = "PJ", nullable = false)
	private String pj;
	
	@Column(name = "AvecMontant", nullable = false)
	private boolean avecMontant;
}
