package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Pjcomplement generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "PJComplement", schema = "dbo")
public class Pjcomplement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CodPj", unique = true, nullable = false, length = 36)
	private String codPj;
	
	@Column(name = "PieceJustificative", nullable = false)
	private String pieceJustificative;

	@Column(name = "Numero")
	private String numero;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePj", length = 23)
	private Date datePj;

	@Column(name = "Montant", precision = 18, scale = 0)
	private Long montant;

	public Pjcomplement(String pieceJustificative, String numero, Date datePj, Long montant) {
		super();
		this.pieceJustificative = pieceJustificative;
		this.numero = numero;
		this.datePj = datePj;
		this.montant = montant;
	}
}
