package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PjengBrseZz generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PJEngBrseZZ", schema = "Elev")
public class PjengBrseZz implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codPj", column = @Column(name = "CodPj", nullable = false, length = 36)),
			@AttributeOverride(name = "numBe", column = @Column(name = "NumBE", nullable = false, precision = 18, scale = 0)) })
	private PjengBrseZzId id;
	
	
	@Column(name = "PieceJustificative")
	private String pieceJustificative;
	
	@Column(name = "Numero")
	private String numero;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePj", length = 23)
	private Date datePj;
	
	@Column(name = "Montant", precision = 18, scale = 0)
	private Long montant;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumBE", nullable = false, insertable = false, updatable = false)
	private Engagements engagements;
}
