package com.sigep.gbc.entity;
// Generated 24 ao�t 2022, 13:59:44 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PlanComptable generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PlanComptable")
public class PlanComptable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdPlan", unique = true, nullable = false)
	private String idPlan;
	
	@Column(name = "IntitulePlan", nullable = false)
	private String intitulePlan;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Niveau", nullable = false)
	private NiveauPlanComptable niveauPlanComptable;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planComptable")
	private List<Budget> budgets = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planComptable")
	private List<EtatVersementElts> etatVersementElts = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planComptable")
	private List<Retenus> retenus = new ArrayList<>();
}
