package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Ppm generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PPM", schema = "dbo")
public class Ppm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdPPM", unique = true, nullable = false, length = 128)
	private String idPpm;
	
	@Column(name = "Exercice", nullable = false)
	private short exercice;
	
	@Column(name = "Num", nullable = false)
	private int num;
	
	@Column(name = "MontantEstime", nullable = false, precision = 18, scale = 0)
	private long montantEstime;
	
	@Column(name = "MontDepEngNonLiq", nullable = false, precision = 18, scale = 0)
	private long montDepEngNonLiq;
	
	@Column(name = "CreditDispo", nullable = false, precision = 18, scale = 0)
	private long creditDispo;
	
	@Column(name = "NatPrestation", nullable = false, length = 850)
	private String natPrestation;
	
	@Column(name = "NbLot", nullable = false)
	private int nbLot;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateLancement", nullable = false, length = 10)
	private Date dateLancement;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateRemiseOffre", nullable = false, length = 10)
	private Date dateRemiseOffre;
	
	@Column(name = "NbJrsEvaluation", nullable = false)
	private int nbJrsEvaluation;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateProbDemar", nullable = false, length = 10)
	private Date dateProbDemar;
	
	@Column(name = "DelaiExecJrs", nullable = false)
	private int delaiExecJrs;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateButoire", nullable = false, length = 10)
	private Date dateButoire;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateEffectLance", length = 10)
	private Date dateEffectLance;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateAttribution", length = 10)
	private Date dateAttribution;
	
	@Column(name = "MontantPasse", nullable = false, precision = 18, scale = 0)
	private long montantPasse;
	
	//Arisitde
	@Column(name="Ream", nullable=false, precision=18, scale=0)
	private long ream;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPPM_M", nullable = false)
	private PpmActe ppmActe;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdModPassation")
	private PpmModePass ppmModePass;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppm")
	private List<PpmOld> ppmOlds = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppm")
	private List<PpmDac> ppmDacs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppm")
	private List<PpmBudg> ppmBudgs = new ArrayList<>();
	
}
