package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PpmActe generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PPM_Acte", schema = "dbo")
public class PpmActe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdPPM_M", unique = true, nullable = false, length = 128)
	private String idPpmM;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;
	
	@Column(name = "Quantieme", nullable = false)
	private int quantieme;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateModif", nullable = false, length = 23)
	private Date dateModif;
	
	@Column(name = "MotifModif", nullable = false, length = 250)
	private String motifModif;
	
	@Column(name = "ActeAutorisation", nullable = false, length = 250)
	private String acteAutorisation;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreate", nullable = false, length = 23)
	private Date dateCreate;
	
	@Column(name = "UserCreate", nullable = false, length = 10)
	private String userCreate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateUpdate", nullable = false, length = 23)
	private Date dateUpdate;
	
	@Column(name = "UserUpdate", nullable = false, length = 10)
	private String userUpdate;
	
	@Column(name = "Valide", nullable = false)
	private boolean valide;
	
	@Column(name = "UserValide", length = 10)
	private String userValide;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateValide", length = 23)
	private Date dateValide;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPPM_M_P")
	private PpmActe ppmActe;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppmActe")
	private List<PpmOld> ppmOlds = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppmActe")
	private List<PpmBudgOld> ppmBudgOlds = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppmActe")
	private List<PpmActe> ppmActes = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppmActe")
	private List<Ppm> ppms = new ArrayList<>();
}
