package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PpmBudgId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class PpmBudgId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "IdPPM", nullable = false, length = 128)
	private String idPpm;
	
	@Column(name = "CodBud", nullable = false)
	private String codBud;
	
	@Column(name = "IdSrceFin", nullable = false)
	private String idSrceFin;
}
