package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PpmBudg generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PPM_BUDG", schema = "dbo")
public class PpmBudg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPpm", column = @Column(name = "IdPPM", nullable = false, length = 128)),
			@AttributeOverride(name = "codBud", column = @Column(name = "CodBud", nullable = false)),
			@AttributeOverride(name = "idSrceFin", column = @Column(name = "IdSrceFin", nullable = false)) })
	private PpmBudgId id;
	
	@Column(name = "MontantEstime", nullable = false, precision = 18, scale = 0)
	private long montantEstime;
	
	@Column(name = "Ream", nullable = false)
	private boolean ream;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdSrceFin", nullable = false, insertable = false, updatable = false)
	private CodSourceFin codSourceFin;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false, insertable = false, updatable = false)
	private Budget budget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPPM", nullable = false, insertable = false, updatable = false)
	private Ppm ppm;
}
