package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PpmBudgOld generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PPM_BudgOld", schema = "dbo")
public class PpmBudgOld implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPpmM", column = @Column(name = "IdPPM_M", nullable = false, length = 128)),
			@AttributeOverride(name = "idPpm", column = @Column(name = "IdPPM", nullable = false, length = 128)),
			@AttributeOverride(name = "codBud", column = @Column(name = "CodBud", nullable = false)),
			@AttributeOverride(name = "idSrceFin", column = @Column(name = "IdSrceFin", nullable = false)) })
	private PpmBudgOldId id;
	
	@Column(name = "MontantEstime", nullable = false, precision = 18, scale = 0)
	private long montantEstime;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPPM_M", nullable = false, insertable = false, updatable = false)
	private PpmActe ppmActe;
}
