package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PpmDac generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PPM_DAC", schema = "dbo")
public class PpmDac implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdDAC", unique = true, nullable = false, length = 128)
	private String idDac;
	
	@Column(name = "RefPassation", nullable = false, length = 150)
	private String refPassation;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreation", nullable = false, length = 23)
	private Date dateCreation;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateDAC", nullable = false, length = 10)
	private Date dateDac;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateLancement", nullable = false, length = 10)
	private Date dateLancement;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPPM")
	private Ppm ppm;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppmDac")
	private List<Contrats> contrats = new ArrayList<>();
}
