package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PpmModePass generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PPM_ModePass", schema = "dbo")
public class PpmModePass implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "AbrevMP", unique = true, nullable = false, length = 10)
	private String abrevMp;
	
	@Column(name = "LibelleLongMP", nullable = false, length = 150)
	private String libelleLongMp;
	
	@Column(name = "JrsLancemt_RemisO", nullable = false)
	private int jrsLancemtRemisO;
	
	@Column(name = "JrsNecessaireEvalua", nullable = false)
	private int jrsNecessaireEvalua;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cod4", nullable = false)
	private CodModPass codModPass;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppmModePass")
	private List<Ppm> ppms = new ArrayList<>();
}
