package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PpmOld generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "PPM_Old", schema = "dbo")
public class PpmOld implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPpmM", column = @Column(name = "IdPPM_M", nullable = false, length = 128)),
			@AttributeOverride(name = "idPpm", column = @Column(name = "IdPPM", nullable = false, length = 128)) })
	private PpmOldId id;
	
	@Column(name = "MontantEstime", nullable = false, precision = 18, scale = 0)
	private long montantEstime;
	
	@Column(name = "MontDepEngNonLiq", nullable = false, precision = 18, scale = 0)
	private long montDepEngNonLiq;
	
	@Column(name = "CreditDispo", nullable = false, precision = 18, scale = 0)
	private long creditDispo;
	
	@Column(name = "NatPrestation", nullable = false, length = 850)
	private String natPrestation;
	
	@Column(name = "NbLot", nullable = false)
	private int nbLot;
	
	@Column(name = "IdModPassation", nullable = false)
	private String idModPassation;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateLancement", nullable = false, length = 10)
	private Date dateLancement;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateRemiseOffre", nullable = false, length = 10)
	private Date dateRemiseOffre;
	
	@Column(name = "NbJrsEvaluation", nullable = false)
	private int nbJrsEvaluation;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateProbDemar", nullable = false, length = 10)
	private Date dateProbDemar;
	
	@Column(name = "DelaiExecJrs", nullable = false)
	private int delaiExecJrs;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateButoire", nullable = false, length = 10)
	private Date dateButoire;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DateEffectLance", length = 10)
	private Date dateEffectLance;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPPM", nullable = false, insertable = false, updatable = false)
	private Ppm ppm;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPPM_M", nullable = false, insertable = false, updatable = false)
	private PpmActe ppmActe;
}
