package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PpmProcedure generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "PPM_Procedure", schema = "dbo")
public class PpmProcedure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdProc", unique = true, nullable = false)
	private Integer idProc;
	
	@Column(name = "LibProcedure", nullable = false, length = 50)
	private String libProcedure;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppmProcedure")
	private List<CodModPass> codModPasss = new ArrayList<>();

	public PpmProcedure(String libProcedure, List<CodModPass> codModPasss) {
		super();
		this.libProcedure = libProcedure;
		this.codModPasss = codModPasss;
	}
}
