package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Reamgmt generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Reamgmt", schema = "dbo")
public class Reamgmt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codReam", column = @Column(name = "CodReam", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "codBug", column = @Column(name = "CodBug", nullable = false)) })
	private ReamgmtId id;
	
	@Column(name = "Ouvert", precision = 18, scale = 0)
	private Long ouvert;

	@Column(name = "Annule", precision = 18, scale = 0)
	private Long annule;

	@Column(name = "Nouvelle", nullable = false)
	private boolean nouvelle;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodReam", nullable = false, insertable = false, updatable = false)
	private ReamgmtActe reamgmtActe;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBug", nullable = false, insertable = false, updatable = false)
	private Budget budget;
}
