package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ReamHvisa generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ReamHVisa", schema = "dbo")
public class ReamHvisa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codReam", column = @Column(name = "CodReam", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "rangVisa", column = @Column(name = "RangVisa", nullable = false)) })
	private ReamHvisaId id;
	
	@Column(name = "LibelleVisa", nullable = false, length = 650)
	private String libelleVisa;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodReam", nullable = false, insertable = false, updatable = false)
	private ReamgmtActe reamgmtActe;
}
