package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ReamgmtActe generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ReamgmtActe", schema = "dbo")
public class ReamgmtActe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "CodReam", unique = true, nullable = false, precision = 18, scale = 0)
	private long codReam;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSaisie", length = 23)
	private Date dateSaisie;

	@Column(name = "Valide", nullable = false)
	private boolean valide;

	@Column(name = "Acte")
	private String acte;

	@Column(name = "Numero")
	private String numero;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateActe", length = 16)
	private Date dateActe;

	@Column(name = "IdLogin", nullable = false, length = 5)
	private String idLogin;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateValid", length = 23)
	private Date dateValid;

	@Column(name = "IdValid", length = 5)
	private String idValid;
	
	@Column(name = "Dep")
	private Boolean dep;

	@Column(name = "ActeTitre", length = 50)
	private String acteTitre;

	@Column(name = "ActeAn", nullable = false)
	private short acteAn;

	@Column(name = "ActeNum")
	private Integer acteNum;

	@Column(name = "ActeNumComplema", length = 50)
	private String acteNumComplema;

	@Column(name = "NumAuto", nullable = false)
	private boolean numAuto;

	@Column(name = "SignataireFonct", length = 150)
	private String signataireFonct;

	@Column(name = "SignataireNom", length = 150)
	private String signataireNom;

	@Column(name = "SignataireTH", length = 150)
	private String signataireTh;

	@Column(name = "ComplemaVisa", length = 5)
	private String complemaVisa;

	@Column(name = "ComplemaVisaLib")
	private String complemaVisaLib;

	@Column(name = "dernierArticleReam", length = 250)
	private String dernierArticleReam;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdActe", nullable = false)
	private ActeNature acteNature;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion")
	private Gestion gestion;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reamgmtActe")
	private List<Reamgmt> reamgmts = new ArrayList<>();

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reamgmtActe")
	private List<ReamHampliation> reamHampliations = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reamgmtActe")
	private List<ReamHvisa> reamHvisas = new ArrayList<>();
}
