package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Recouvrements generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Recouvrements", schema = "dbo")
public class Recouvrements implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CodRecouv", unique = true, nullable = false, length = 36)
	private String codRecouv;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", nullable = false, length = 23)
	private Date date;
	

	@Column(name = "Objet", nullable = false)
	private String objet;
	
	@Column(name = "RefQuittance")
	private String refQuittance;

	@Column(name = "IndenteVersant")
	private String indenteVersant;

	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;
	

	@Column(name = "IdLogin", nullable = false, length = 5)
	private String idLogin;
	
	@Column(name = "Report")
	private Boolean report;

	@Column(name = "ID")
	private String id;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePosition", length = 16)
	private Date datePosition;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEtat", nullable = false, length = 23)
	private Date dateEtat;

	@Column(name = "CodBord", precision = 18, scale = 0)
	private Long codBord;

	@Column(name = "ModPaieNum", length = 150)
	private String modPaieNum;
	

	@Temporal(TemporalType.DATE)
	@Column(name = "ModPaieDate", length = 10)
	private Date modPaieDate;

	@Column(name = "UserCreate", nullable = false, length = 5)
	private String userCreate;
	
	@Column(name = "PrenomNomSigna")
	private String prenomNomSigna;

	@Column(name = "AGenerer", nullable = false)
	private boolean agenerer;

	@Column(name = "QR_code")
	private byte[] qrCode;

	@Column(name = "QuantiemeAn", nullable = false, precision = 18, scale = 0)
	private long quantiemeAn;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateE", nullable = false, length = 23)
	private Date dateE;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false)
	private Budget budget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCptRep", nullable = false)
	private Compte compte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDebiteur", nullable = false)
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtatTrans", nullable = false)
	private EtatTransmission etatTransmission;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false)
	private Gestion gestion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand")
	private Mandats mandats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ModVers", nullable = false)
	private ModePaiement modePaiement;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Etat", nullable = false)
	private EtatDossier etatDossier;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recouvrements")
	private List<TitreEmis> titreEmis = new ArrayList<>();
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "recouvrementss")
	private List<TitreEmis> titreEmiss = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recouvrements")
	private List<BordTransRecouv> bordTransRecouvs = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recouvrements")
	private List<JournalPiece> journalPieces = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recouvrements")
	private List<CompteMouvEtatVelts> compteMouvEtatVelts = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recouvrements")
	private List<AcompteFrais> acompteFrais = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recouvrements")
	private List<RecouvrementBilletage> recouvrementBilletages = new ArrayList<>();

	public Recouvrements(Date date, String objet, String refQuittance, String indenteVersant, long montant,
			String idLogin, Boolean report, String id, Date datePosition, Date dateEtat, Long codBord,
			String modPaieNum, Date modPaieDate, String userCreate, String prenomNomSigna, boolean agenerer,
			byte[] qrCode, long quantiemeAn, Date dateE, Budget budget, BudgetType budgetType, Compte compte,
			Destinataires destinataires, EtatTransmission etatTransmission, Gestion gestion, Mandats mandats,
			ModePaiement modePaiement, EtatDossier etatDossier, List<TitreEmis> titreEmis, List<TitreEmis> titreEmiss,
			List<BordTransRecouv> bordTransRecouvs, List<JournalPiece> journalPieces,
			List<CompteMouvEtatVelts> compteMouvEtatVelts, List<AcompteFrais> acompteFrais,
			List<RecouvrementBilletage> recouvrementBilletages) {
		super();
		this.date = date;
		this.objet = objet;
		this.refQuittance = refQuittance;
		this.indenteVersant = indenteVersant;
		this.montant = montant;
		this.idLogin = idLogin;
		this.report = report;
		this.id = id;
		this.datePosition = datePosition;
		this.dateEtat = dateEtat;
		this.codBord = codBord;
		this.modPaieNum = modPaieNum;
		this.modPaieDate = modPaieDate;
		this.userCreate = userCreate;
		this.prenomNomSigna = prenomNomSigna;
		this.agenerer = agenerer;
		this.qrCode = qrCode;
		this.quantiemeAn = quantiemeAn;
		this.dateE = dateE;
		this.budget = budget;
		this.budgetType = budgetType;
		this.compte = compte;
		this.destinataires = destinataires;
		this.etatTransmission = etatTransmission;
		this.gestion = gestion;
		this.mandats = mandats;
		this.modePaiement = modePaiement;
		this.etatDossier = etatDossier;
		this.titreEmis = titreEmis;
		this.titreEmiss = titreEmiss;
		this.bordTransRecouvs = bordTransRecouvs;
		this.journalPieces = journalPieces;
		this.compteMouvEtatVelts = compteMouvEtatVelts;
		this.acompteFrais = acompteFrais;
		this.recouvrementBilletages = recouvrementBilletages;
	}
}
