package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * RecouvrementBilletage generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Recouvrement_Billetage", schema = "dbo")
public class RecouvrementBilletage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "designa", column = @Column(name = "Designa", nullable = false, length = 1)),
			@AttributeOverride(name = "coupure", column = @Column(name = "Coupure", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "codRecouv", column = @Column(name = "CodRecouv", nullable = false, length = 36)) })
	private RecouvrementBilletageId id;
	
	@Column(name = "Nombre", nullable = false, precision = 18, scale = 0)
	private long nombre;

	@Column(name = "Total", precision = 37, scale = 0)
	private BigInteger total;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodRecouv", nullable = false, insertable = false, updatable = false)
	private Recouvrements recouvrements;
}
