package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * RecouvrementBilletageId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class RecouvrementBilletageId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "Designa", nullable = false, length = 1)
	private String designa;

	@Column(name = "Coupure", nullable = false, precision = 18, scale = 0)
	private long coupure;

	@Column(name = "CodRecouv", nullable = false, length = 36)
	private String codRecouv;
}
