package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ReportAnouveau generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ReportANouveau", schema = "dbo")
public class ReportAnouveau implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdReport", unique = true, nullable = false, precision = 18, scale = 0)
	private long idReport;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreat", nullable = false, length = 23)
	private Date dateCreat;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCloture", nullable = false, length = 23)
	private Date dateCloture;
	
	@Column(name = "GestionClos", nullable = false)
	private short gestionClos;
	
	@Column(name = "Comptable", nullable = false)
	private boolean comptable;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reportAnouveau")
	private List<JournalPiece> journalPieces = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reportAnouveau")
	private List<ReportBudgetaire> reportBudgetaires = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reportAnouveau")
	private List<ReportCompte> reportComptes = new ArrayList<>();
}
