package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ReportCompte generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ReportCompte", schema = "dbo")
public class ReportCompte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idCompte", column = @Column(name = "IdCompte", nullable = false)),
			@AttributeOverride(name = "gestion", column = @Column(name = "Gestion", nullable = false)),
			@AttributeOverride(name = "idReport", column = @Column(name = "IdReport", nullable = false, precision = 18, scale = 0)) })
	private ReportCompteId id;
	
	@Column(name = "Debiter", nullable = false, precision = 18, scale = 0)
	private long debiter;

	@Column(name = "Crediter", nullable = false, precision = 18, scale = 0)
	private long crediter;

	@Column(name = "Report", nullable = false)
	private boolean report;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdReport", nullable = false, insertable = false, updatable = false)
	private ReportAnouveau reportAnouveau;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCompte", nullable = false, insertable = false, updatable = false)
	private Compte compte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false, insertable = false, updatable = false)
	private Gestion gestion;
}
