package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ReportDetail generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ReportDetail", schema = "dbo")
public class ReportDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idReport", column = @Column(name = "IdReport", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "section", column = @Column(name = "Section", nullable = false, length = 1)),
			@AttributeOverride(name = "titre", column = @Column(name = "Titre", nullable = false, length = 1)),
			@AttributeOverride(name = "gestion", column = @Column(name = "Gestion", nullable = false)),
			@AttributeOverride(name = "codBud", column = @Column(name = "CodBud", nullable = false)) })
	private ReportDetailId id;
	
	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEnreg", nullable = false, length = 23)
	private Date dateEnreg;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "IdReport", referencedColumnName = "IdReport", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Section", referencedColumnName = "Section", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Titre", referencedColumnName = "Titre", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Gestion", referencedColumnName = "Gestion", nullable = false, insertable = false, updatable = false) })
	private ReportBudgetaire reportBudgetaire;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false, insertable = false, updatable = false)
	private Budget budget;
}
