package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ReportCompteId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class ReportCompteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "IdCompte", nullable = false)
	private String idCompte;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;

	@Column(name = "IdReport", nullable = false, precision = 18, scale = 0)
	private long idReport;
}
