package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ReportBudgetaire generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ReportBudgetaire", schema = "dbo")
public class ReportBudgetaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idReport", column = @Column(name = "IdReport", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "section", column = @Column(name = "Section", nullable = false, length = 1)),
			@AttributeOverride(name = "titre", column = @Column(name = "Titre", nullable = false, length = 1)),
			@AttributeOverride(name = "gestion", column = @Column(name = "Gestion", nullable = false)) })
	private ReportBudgetaireId id;
	
	@Column(name = "Libelle", nullable = false, length = 150)
	private String libelle;

	@Column(name = "Solde", nullable = false, precision = 18, scale = 0)
	private long solde;

	@Column(name = "Resultat", nullable = false, length = 9)
	private String resultat;

	@Column(name = "Report", nullable = false)
	private boolean report;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdReport", nullable = false, insertable = false, updatable = false)
	private ReportAnouveau reportAnouveau;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false, insertable = false, updatable = false)
	private Gestion gestion;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reportBudgetaire")
	private List<ReportDetail> reportDetails = new ArrayList<>();
}
