package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ReportDetailId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class ReportDetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "IdReport", nullable = false, precision = 18, scale = 0)
	private long idReport;

	@Column(name = "Section", nullable = false, length = 1)
	private String section;

	@Column(name = "Titre", nullable = false, length = 1)
	private String titre;

	@Column(name = "Gestion", nullable = false)
	private short gestion;

	@Column(name = "CodBud", nullable = false)
	private String codBud;
}
