package com.sigep.gbc.entity;
// Generated 25 nov. 2022, 12:52:25 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * RetenueCategorie generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "RetenueCategorie")
public class RetenueCategorie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdCategorie", unique = true, nullable = false)
	private String idCategorie;
	
	@Column(name = "Libelle")
	private String libelle;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retenueCategorie")
	private List<RetenuType> retenuTypes = new ArrayList<>();
}
