package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * RetenusQuitOrdre generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Retenus_QuitOrdre", schema = "dbo")
public class RetenusQuitOrdre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idQitO", unique = true, nullable = false, length = 36)
	private String idQitO;
	
	@Column(name = "Anne", nullable = false)
	private int anne;

	@Column(name = "QuantiemeAn", nullable = false, precision = 18, scale = 0)
	private long quantiemeAn;

	@Column(name = "RefQuittance")
	private String refQuittance;

	@Column(name = "QR_code")
	private byte[] qrCode;

	@Column(name = "Edite", nullable = false)
	private boolean edite;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand", nullable = false)
	private Mandats mandats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRetenu")
	private Retenus retenus;

	public RetenusQuitOrdre(int anne, long quantiemeAn, String refQuittance, byte[] qrCode, boolean edite,
			Mandats mandats, Retenus retenus) {
		super();
		this.anne = anne;
		this.quantiemeAn = quantiemeAn;
		this.refQuittance = refQuittance;
		this.qrCode = qrCode;
		this.edite = edite;
		this.mandats = mandats;
		this.retenus = retenus;
	}
}
