package com.sigep.gbc.entity;
// Generated 25 nov. 2022, 12:52:25 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * RetenuType generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "RetenuType", uniqueConstraints = @UniqueConstraint(columnNames = "Libelle"))
public class RetenuType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdTypRetenu", unique = true, nullable = false)
	private Integer idTypRetenu;
	
	@Column(name = "Libelle", unique = true, nullable = false, length = 550)
	private String libelle;
	
	@Column(name = "Taux", nullable = false, precision = 18)
	private BigDecimal taux;
	
	@Column(name = "LibelleCpte")
	private String libelleCpte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodCpte", nullable = false)
	private Compte compte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Categorie", nullable = false)
	private RetenueCategorie retenueCategorie;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retenuType")
	private List<Retenus> retenus = new ArrayList<>();

	public RetenuType(String libelle, BigDecimal taux, String libelleCpte, Compte compte,
			RetenueCategorie retenueCategorie) {
		super();
		this.libelle = libelle;
		this.taux = taux;
		this.libelleCpte = libelleCpte;
		this.compte = compte;
		this.retenueCategorie = retenueCategorie;
	}
}
