package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * RetenuTitreRecouv generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "RetenuTitreRecouv", schema = "dbo")
public class RetenuTitreRecouv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "retenus"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IDRTR", unique = true, nullable = false, length = 36)
	private String idrtr;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateConsideration", nullable = false, length = 23)
	private Date dateConsideration;

	@Column(name = "Objet", nullable = false)
	private String objet;

	@Column(name = "RefQuittance")
	private String refQuittance;
	
	@Column(name = "Montant", nullable = false, precision = 18, scale = 0)
	private long montant;

	@Column(name = "IdCpteD", nullable = false)
	private String idCpteD;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePosition", length = 16)
	private Date datePosition;

	@Column(name = "UserCreate", nullable = false, length = 5)
	private String userCreate;

	@Column(name = "PrenomNomSigna")
	private String prenomNomSigna;

	@Column(name = "AGenerer", nullable = false)
	private boolean agenerer;

	@Column(name = "QR_code")
	private byte[] qrCode;

	@Column(name = "QuantiemeAn", nullable = false, precision = 18, scale = 0)
	private long quantiemeAn;

	@Column(name = "DemandeTitre", nullable = false)
	private boolean demandeTitre;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateE", nullable = false, length = 23)
	private Date dateE;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand")
	private Mandats mandats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ModVers", nullable = false)
	private ModePaiement modePaiement;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Retenus retenus;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false)
	private Gestion gestion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false)
	private Budget budget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCpteC")
	private Compte compte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDebiteur")
	private Destinataires destinataires;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retenuTitreRecouv")
	private List<JournalPiece> journalPieces = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retenuTitreRecouv")
	private List<TitreEmis> titreEmis = new ArrayList<>();

	public RetenuTitreRecouv(Date dateConsideration, String objet, String refQuittance, long montant, String idCpteD,
			Date datePosition, String userCreate, String prenomNomSigna, boolean agenerer, byte[] qrCode,
			long quantiemeAn, boolean demandeTitre, Date dateE, Mandats mandats, ModePaiement modePaiement,
			Retenus retenus, Gestion gestion, Budget budget, BudgetType budgetType, Compte compte,
			Destinataires destinataires, List<JournalPiece> journalPieces, List<TitreEmis> titreEmis) {
		super();
		this.dateConsideration = dateConsideration;
		this.objet = objet;
		this.refQuittance = refQuittance;
		this.montant = montant;
		this.idCpteD = idCpteD;
		this.datePosition = datePosition;
		this.userCreate = userCreate;
		this.prenomNomSigna = prenomNomSigna;
		this.agenerer = agenerer;
		this.qrCode = qrCode;
		this.quantiemeAn = quantiemeAn;
		this.demandeTitre = demandeTitre;
		this.dateE = dateE;
		this.mandats = mandats;
		this.modePaiement = modePaiement;
		this.retenus = retenus;
		this.gestion = gestion;
		this.budget = budget;
		this.budgetType = budgetType;
		this.compte = compte;
		this.destinataires = destinataires;
		this.journalPieces = journalPieces;
		this.titreEmis = titreEmis;
	}
}
