package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Retenus generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Retenus", schema = "dbo")
public class Retenus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idRetenu", unique = true, nullable = false, length = 36)
	private String idRetenu;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateRetenu", length = 23)
	private Date dateRetenu;

	@Column(name = "Montant", precision = 18, scale = 0)
	private Long montant;

	@Column(name = "Paie")
	private Boolean paie;
	
	@Column(name = "CodBud")
	private String codBud;
	
	@Column(name = "Recette", nullable = false)
	private boolean recette;

	@Column(name = "RefQuittance")
	private String refQuittance;

	@Column(name = "Taux", nullable = false, precision = 18)
	private BigDecimal taux;
	
	@Column(name = "MontantBrut", precision = 18, scale = 0)
	private Long montantBrut;

	@Column(name = "ConsidereRecette", nullable = false)
	private boolean considereRecette;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idContrat")
	private Contrats contrats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NumMand")
	private Mandats mandats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPenal")
	private Penalite penalite;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdTypRetenu")
	private RetenuType retenuType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCpte", nullable = false)
	private PlanComptable planComptable;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDest")
	private Destinataires destinataires;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retenus")
	private List<CompteMouvRetenu> compteMouvRetenus = new ArrayList<>();
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "retenus")
	private RetenuTitreRecouv retenuTitreRecouv;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retenus")
	private List<RetenusQuitOrdre> retenusQuitOrdres = new ArrayList<>();

	public Retenus(Date dateRetenu, Long montant, Boolean paie, String codBud, boolean recette, String refQuittance,
			BigDecimal taux, Long montantBrut, boolean considereRecette, Contrats contrats, Mandats mandats,
			Penalite penalite, RetenuType retenuType, PlanComptable planComptable, Destinataires destinataires,
			List<CompteMouvRetenu> compteMouvRetenus, RetenuTitreRecouv retenuTitreRecouv,
			List<RetenusQuitOrdre> retenusQuitOrdres) {
		super();
		this.dateRetenu = dateRetenu;
		this.montant = montant;
		this.paie = paie;
		this.codBud = codBud;
		this.recette = recette;
		this.refQuittance = refQuittance;
		this.taux = taux;
		this.montantBrut = montantBrut;
		this.considereRecette = considereRecette;
		this.contrats = contrats;
		this.mandats = mandats;
		this.penalite = penalite;
		this.retenuType = retenuType;
		this.planComptable = planComptable;
		this.destinataires = destinataires;
		this.compteMouvRetenus = compteMouvRetenus;
		this.retenuTitreRecouv = retenuTitreRecouv;
		this.retenusQuitOrdres = retenusQuitOrdres;
	}
}
