package com.sigep.gbc.entity;
// Generated 21 févr. 2023, 13:48:54 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * StElements generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "ST_Elements")
public class StElements implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdST_Elts", unique = true, nullable = false, length = 36)
	private String idStElts;
	
	@Column(name = "Partie", nullable = false)
	private int partie;
	
	@Column(name = "RangST_Elts", nullable = false)
	private int rangStElts;
	
	@Column(name = "LibelleST_Elts", nullable = false, length = 50)
	private String libelleStElts;
	
	@Column(name = "CompletLib", nullable = false, length = 5)
	private String completLib;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stElements")
	private List<StElementsNomencla> stElementsNomenclas = new ArrayList<>();

	public StElements(int partie, int rangStElts, String libelleStElts, String completLib,
			List<StElementsNomencla> stElementsNomenclas) {
		super();
		this.partie = partie;
		this.rangStElts = rangStElts;
		this.libelleStElts = libelleStElts;
		this.completLib = completLib;
		this.stElementsNomenclas = stElementsNomenclas;
	}
}
