package com.sigep.gbc.entity;
// Generated 21 févr. 2023, 13:48:54 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * StElementsNomencla generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ST_ElementsNomencla")
public class StElementsNomencla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idStElts", column = @Column(name = "IdST_Elts", nullable = false, length = 36)),
			@AttributeOverride(name = "gestion", column = @Column(name = "Gestion", nullable = false)),
			@AttributeOverride(name = "idPlan", column = @Column(name = "IdPlan", nullable = false)) })
	private StElementsNomenclaId id;
	
	@Column(name = "Op", nullable = false, length = 1)
	private String op;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdST_Elts", nullable = false, insertable = false, updatable = false)
	private StElements stElements;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gestion", nullable = false, insertable = false, updatable = false)
	private Gestion gestion;
}
