package com.sigep.gbc.entity;
// Generated 21 févr. 2023, 13:48:54 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * StElementsNomenclaId generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Embeddable
public class StElementsNomenclaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "IdST_Elts", nullable = false, length = 36)
	private String idStElts;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;
	
	@Column(name = "IdPlan", nullable = false)
	private String idPlan;
}
