package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Suspension generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "Suspension", schema = "dbo")
public class Suspension implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdSus", unique = true, nullable = false, length = 36)
	private String idSus;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateDemar", length = 23)
	private Date dateDemar;

	@Column(name = "RefActe1")
	private String refActe1;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateSusp", length = 23)
	private Date dateSusp;
	
	@Column(name = "RefActe2")
	private String refActe2;

	@Column(name = "Nbjrs")
	private Integer nbjrs;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateActDemarReprise", length = 16)
	private Date dateActDemarReprise;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateAcSuspens", length = 16)
	private Date dateAcSuspens;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdContrat")
	private Contrats contrats;

	public Suspension(Date dateDemar, String refActe1, Date dateSusp, String refActe2, Integer nbjrs,
			Date dateActDemarReprise, Date dateAcSuspens, Contrats contrats) {
		super();
		this.dateDemar = dateDemar;
		this.refActe1 = refActe1;
		this.dateSusp = dateSusp;
		this.refActe2 = refActe2;
		this.nbjrs = nbjrs;
		this.dateActDemarReprise = dateActDemarReprise;
		this.dateAcSuspens = dateAcSuspens;
		this.contrats = contrats;
	}
}
