package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TiersCaissePop generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "TiersCaissePop", schema = "dbo")
public class TiersCaissePop implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "destinataires"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IdCaissePop", unique = true, nullable = false, precision = 18, scale = 0)
	private long idCaissePop;
	
	@Column(name = "CaissePop", nullable = false)
	private String caissePop;
	
	@Column(name = "Folio", nullable = false, length = 50)
	private String folio;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Destinataires destinataires;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiersCaissePop")
	private List<CompteDestinataire> compteDestinataires = new ArrayList<>();

	public TiersCaissePop(String caissePop, String folio, Destinataires destinataires,
			List<CompteDestinataire> compteDestinataires) {
		super();
		this.caissePop = caissePop;
		this.folio = folio;
		this.destinataires = destinataires;
		this.compteDestinataires = compteDestinataires;
	}
}
