package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TitreInscritPour generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "TitreInscritPour", schema = "Elev")
public class TitreInscritPour implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDebiteur", column = @Column(name = "IdDebiteur", nullable = false)),
			@AttributeOverride(name = "anneInscription", column = @Column(name = "AnneInscription", nullable = false)),
			@AttributeOverride(name = "anneD", column = @Column(name = "AnneD", nullable = false)),
			@AttributeOverride(name = "idFrais", column = @Column(name = "IdFrais", nullable = false)),
			@AttributeOverride(name = "codTitr", column = @Column(name = "CodTitr", nullable = false, length = 36)) })
	private TitreInscritPourId id;
	
	@Column(name = "IdDetailTitre", nullable = false, precision = 18, scale = 0)
	private long idDetailTitre;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodTitr", nullable = false, insertable = false, updatable = false)
	private TitreEmis titreEmis;
}
