package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TitreEmis generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "TitreEmis", schema = "dbo")
public class TitreEmis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CodTitr", unique = true, nullable = false, length = 36)
	private String codTitr;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;
	
	@Column(name = "Objet")
	private String objet;
	
	@Column(name = "Montant", precision = 18, scale = 0)
	private Long montant;
	
	@Column(name = "Auto", nullable = false)
	private boolean auto;
	
	@Column(name = "idRetenu", length = 36)
	private String idRetenu;
	
	@Column(name = "AnneeOrigine")
	private Integer anneeOrigine;
	
	@Column(name = "MontantRecouvre", nullable = false, precision = 18, scale = 0)
	private long montantRecouvre;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud")
	private Budget budget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCompte")
	private Compte compte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDebiteur")
	private Destinataires destinataires;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdFact")
	private Factures factures;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodRecouv")
	private Recouvrements recouvrements;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDRTR")
	private RetenuTitreRecouv retenuTitreRecouv;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDetailTitre")
	private TitreDetail titreDetail;
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(
			name = "TitreRecouv", schema = "dbo", 
			joinColumns = {@JoinColumn(name = "CodTitr", nullable = false, updatable = false) }, 
			inverseJoinColumns = {@JoinColumn(name = "CodRecouv", nullable = false, updatable = false) })
	private List<Recouvrements> recouvrementss = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titreEmis")
	private List<AcompteFrais> acompteFrais = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titreEmis")
	private List<JournalPiece> journalPieces = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titreEmis")
	private List<TitreInscritPour> titreInscritPours = new ArrayList<>();
	
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "titreEmis")
	private TitreEmisCloture titreEmisCloture;	
}
