package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TitreEmisCloture generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@Table(name = "TitreEmisCloture", schema = "dbo")
public class TitreEmisCloture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "titreEmis"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CodTitr", unique = true, nullable = false, length = 36)
	private String codTitr;
	
	@Column(name = "Observations", length = 1050)
	private String observations;
	
	@Column(name = "Apurer", nullable = false)
	private boolean apurer;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private TitreEmis titreEmis;

	public TitreEmisCloture(String observations, boolean apurer, TitreEmis titreEmis) {
		super();
		this.observations = observations;
		this.apurer = apurer;
		this.titreEmis = titreEmis;
	}
}
