package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TitreDetail generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "TitreDetail", schema = "dbo")
public class TitreDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "IdDetailTitre", unique = true, nullable = false, precision = 18, scale = 0)
	private long idDetailTitre;
	
	@Column(name = "Montant", precision = 18, scale = 0)
	private Long montant;
	
	@Column(name = "Gestion", nullable = false)
	private short gestion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", nullable = false, length = 23)
	private Date date;
	
	@Column(name = "Reftitre")
	private String reftitre;
	
	@Column(name = "IdLogin", length = 5)
	private String idLogin;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateEtat", nullable = false, length = 23)
	private Date dateEtat;
	
	@Column(name = "Numero", precision = 18, scale = 0)
	private Long numero;
	
	@Column(name = "NumAuto")
	private Boolean numAuto;
	
	@Column(name = "TitreSignataire", length = 250)
	private String titreSignataire;
	
	@Column(name = "NumComplema", nullable = false, length = 40)
	private String numComplema;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatePEC", length = 23)
	private Date datePec;
	
	@Column(name = "Receptionne", nullable = false)
	private boolean receptionne;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateValid", nullable = false, length = 23)
	private Date dateValid;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Mle")
	private Agents agents;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBudget", nullable = false)
	private BudgetType budgetType;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBud", nullable = false)
	private Budget budget;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdBordEmis")
	private BordereauEmismandats bordereauEmismandats;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodBord")
	private BordTransmis bordTransmis;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Etat", nullable = false)
	private EtatDossier etatDossier;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtatTrans", nullable = false)
	private EtatTransmission etatTransmission;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdApartir", nullable = false)
	private TitreRegulApartir titreRegulApartir;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titreDetail")
	private List<BordTitre> bordTitres = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titreDetail")
	private List<TitreEmis> titreEmis = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titreDetail")
	private List<AcompteFrais> acompteFrais = new ArrayList<>();
}
