package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TitreRegulApartir generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "TitreRegulApartir", schema = "dbo")
public class TitreRegulApartir implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "IdApartir", unique = true, nullable = false)
	private int idApartir;
	
	@Column(name = "LibelleApartir", nullable = false, length = 50)
	private String libelleApartir;
	
	@Column(name = "Regularisation", nullable = false)
	private boolean regularisation;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titreRegulApartir")
	private List<TitreDetail> titreDetails = new ArrayList<>();
}
