package com.sigep.gbc.entity;
// Generated 31 janv. 2023, 14:11:42 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * TypeDecision generated by hbm2java
 */

@Entity
@Data
@NoArgsConstructor
@Table(name = "TypeDecision")
public class TypeDecision implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdType", unique = true, nullable = false)
	private Integer idType;
	
	@Column(name = "Libelle")
	private String libelle;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeDecision")
	private List<DecisionSvisa> decisionSvisas = new ArrayList<>();

	public TypeDecision(String libelle, List<DecisionSvisa> decisionSvisas) {
		super();
		this.libelle = libelle;
		this.decisionSvisas = decisionSvisas;
	}
}
