package com.sigep.gbc.entity;
// Generated 20 juin 2023, 12:25:46 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TypesFrais generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "TypesFrais", schema = "Elev")
public class TypesFrais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "TypeFrais", unique = true, nullable = false)
	private int typeFrais;
	
	@Column(name = "LibTypeFrais", nullable = false)
	private String libTypeFrais;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typesFrais")
	private List<FraisInscription> fraisInscriptions = new ArrayList<>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typesFrais")
	private List<Pays> pays = new ArrayList<>();
}
