package com.sigep.gbc.view.dto;

import java.util.Date;


import lombok.Data;

@Data
public class EngagementEN02ViewDto {
	private long numBe;
	private String codBud;
	private short gestion;
	private int benum;
	private String proced;
	private Date dateCreation;
	private String natDepense;
	private String auProfit;
	private long montant;
	private Long dot_Initiale;
	private Long dispoAvant;
	private String etat;
	private Date dateEtat;
	private Long idBord;
	private Long idFourn;
	private Long idContrat;
	private Long idEng;
	private String idUser;
	private Integer idEtatTrans;
	private Integer idBudget;
	private boolean avecDecision;
	private Long codLiq;
	private boolean apartirDemandLiq;
	private boolean grh;
	private boolean receptionne;
	private Date dateValid;
	private Date dateCreat;
	private String intitule;
	private long dotInitiale;
	private long totalEngag;
	private Long dotationCorrigee;
	private Long dotationDefinitive;
	private Long disponible;
	private long nbreEngag;
	private String ifumle;
	private String ftype;
	private String nom;
	private String titre;
	private String section;
	private String chap;
	private String art;
	private String parag;
	private String rub;
	private Integer numeroContrat; // Contrat
	private String referenceContrat;
	private Date dateSaisieContrat;
	private long montantContrat;
	private Long engageContrat;
	private Long engageContratPourModifierEngagement;
	private Long mandateContrat;
	private Long engageValidContrat;
	private Long mandateValidContrat;
	private Long resteAEngagerContrat;
	private Long resteAEngagerContratPourModifierEngagement;
	private Long resteALiquiderContrat;
	private Long numMand;// Mandat
	private Integer mandNumb;
	private Date dateMand;
	private Long montantMand;
	private String etatMand;
	private Date dateEtatMand;
	private String compteFourn;
	private Date datePaie;
	private Long montantPaie;
	private String idModePaie;
	private String idCompte;
	private Date datePosition;
	private Integer numBl;
	private Long montEngage;
	private Long montDjaLiq;
	private String etatBl;
	private Date dateEtatBl;
	private Long numMandParent;
	private String idBordEmisMand;
	private Long idbordMand;
	private Integer idEtatTransM;
	private Integer idEtatTransL;
	private String idLettrage;
	private Date datePec;
	private Boolean receptionneMand;
	private Boolean genererOv;
	private Boolean avecReversement;
	private Long precompte;
	private Date datePrecompte;
	private String userPrecompte;
	private Date dateValidMand;
	private Long idFiche;
	private Long montantTotalPec;
	private Date date_CreatMand;
	private Boolean estOrdre;
	private Integer mandNumApresVisaCf;
	private String codeBanque;
	private String codeAgence;
	private String numCompte;
	private String cleRib;
	private String caissePop;
	private String numCaissePop;
	private String codeBic;
	private String iban;
	private Long idCaissePop;
	private String abreviation;
	private String idAgence;
	private String libelleAgence;
	private String domicilieA;
	private Long dejaLiquide;
	private Long resteALiquider;
	private String id_motif;
	private String motifs;
	private Date dateSaisieMotif;
	private Long idTitreMotif;
	private String userNameMotif;
	private Date dateEnregMotif;
	private boolean actifMotif;
}