package com.sigep.gbc.view.dto;

import java.util.Date;

import lombok.Data;

@Data
public class LiquidationViewDto {
	private long codLiq;
	private long numBe;
	private short gestion;
	private int numBl;
	private Date dateLiq;
	private String objet;
	private long montant;
	private long montEngage;
	private long montDjaLiq;
	private boolean modifiable;
	private Long idFourn;
	private Long idContrat;
	private String idUser;
	private String compteFourn;
	private String numeroDemande;
	private Date dateModif;
	private boolean actif;
	private int idBudget;
	private String codBud;
	private int benum;
	private String proced;
	private Date dateCreationEng;
	private long montantEng;
	private long dejaLiquideEng;
	private long dejaLiquideReelEng;
	private long resteALiquiderEng;
	private long resteALiquiderReelEng;
	private long nbreLiqEng;
	private long nbreLiqReelEng;
	private String ifumle;
	private String nom;
	private String titre;
	private String section;
	private String chap;
	private String art;
	private String parag;
	private String rub;
	private String intitule;
	private Integer numeroContrat;// Contrat
	private String referenceContrat;
	private Date dateSaisieContrat;
	private Long montantContrat;
	private Long engageContrat;
	private Long mandateContrat;
	private Long engageValidContrat;
	private Long mandateValidContrat;
	private Long numMand;// Mandat
	private Integer mandNumb;
	private Date dateMand;
	private Long montantMand;
	private String etatMand;
	private Date dateEtatMand;
	private String compteFournMand;
	private Date datePaieMand;
	private Long montantPaieMand;
	private String idModePaieMand;
	private String idCompteMand;
	private Date datePositionMand;
	private Integer numBlMand;
	private Long montEngageMand;
	private Long montDjaLiqMand;
	private String etatBlMand;
	private Date dateEtatBlMand;
	private Long numMandParent;
	private String idBordEmisMand;
	private Long idbordMand;
	private Integer idEtatTransMMand;
	private Integer idEtatTransLMand;
	private String idLettrageMand;
	private Date datePecMand;
	private Boolean receptionneMand;
	private Boolean genererOvMand;
	private Boolean avecReversementMand;
	private Long precompteMand;
	private Date datePrecompteMand;
	private String userPrecompteMand;
	private Date dateValidMand;
	private Long idFicheMand;
	private Long montantTotalPecMand;
	private Date date_CreatMandMand; 
	private Boolean estOrdreMand;
	private Integer mandNumApresVisaCf;
	private String abreviation;
	private String codeBanque;
	private String codeAgence;
	private String numCompte;
	private String cleRib;
	private String caissePop;
	private String numCaissePop;
	private String idAgence;
	private String codeBic;
	private String iban;
	private Long idCaissePop;
	private String libelleAgence;
	private String domicilieA;
}