package com.sigep.common.histoGbk.entity;
// Generated 24 ao�t 2022, 13:59:44 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * BudgetType generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BudgetType")
public class BudgetType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdBudget", unique = true, nullable = false)
	private Integer idBudget;
	
	@Column(name = "LibelleBudget", nullable = false, length = 150)
	private String libelleBudget;
	
	@Column(name = "LibelleDecision", nullable = false, length = 250)
	private String libelleDecision;
}
