package com.sigep.common.histoGbk.entity;
// Generated 27 juin 2022, 18:53:35 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * EnteteStructure generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "EnteteStructure")
public class EnteteStructure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	private String abrevEpe;
	
	private String section;
	private String epe;
	private String lieu;
	
	@Lob
	@Column(name = "logo")
	private byte[] logo;
	
	private String signataireDg;
	private String nomSignataireDg;
	private String titreHonorifiqueDg;
	private String signataireDaf;
	private String nomSignataireDaf;
	private String titreHonorifiqueDaf;
	private String signataireCf;
	private String nomSignataireCf;
	private String titreHonorifiqueCf;
	private String signataireAc;
	private String nomSignataireAc;
	private String titreHonorifiqueAc;
	private Boolean cfresident;
	private Boolean signatPenal;
	private String adresse;
	private String telephone;
	private String fax;
	private String email;
	private String visa;
	private String articleStruct;
	private String nomPays;
	private String devisePays;
	private String mleCnss;
	private String mleCarfo;
	private int typeSupport;
	private boolean avecReception;
	
	@Lob
	@Column(name = "QuitFiligrane")
	private byte[] quitFiligrane;
	
	private BigDecimal tauxTva;
	private char typeAmmortDefaut;
	private boolean gbc;
	private boolean gim;
	private boolean grh;
	private String sectionNum;
	
	@Lob
	@Column(name = "FilgraneL27_6cmH18_5cm")
	private byte[] filgraneL276cmH185cm;
	
	private String signataireDrh;
	private String nomSignataireDrh;
	private String titreHonorifiqueDrh;
	private int idCircuitGrh;
	private boolean drhsigneEtat;
	private String libAnnee;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mandNumApresVisaCf", nullable = false)
	private NumerotationMandat numerotationMandat;
}
