package com.sigep.common.histoGbk.entity;
// Generated 16 ao�t 2022, 19:00:48 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Gestion generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Gestion")
public class Gestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "Courante", unique = true, nullable = false)
	private short courante;
	
	@Column(name = "Libelle")
	private String libelle;
	
	@Column(name = "Etat")
	private String etat;
	
	@Column(name = "utilisation")
	private String utilisation;
}
