package com.sigep.common.histoGbk.entity;
// Generated 27 juin 2022, 18:53:35 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * NumerotationMandat generated by hbm2java
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "NumerotationMandat")
public class NumerotationMandat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	private int mandNumApresVisaCf;
	
	@Column(name = "descriptions", nullable = false)
	private String descriptions;
}
